/* ELF '26 — Premier League 2025/26 club squads (summer 2025 transfers applied).
   [name, rating, positions("/"-sep, primary first), age]. Aggressive 2025/26 scale. */
window.CLUBS_ENG = [
  { name:"Liverpool", short:"Liverpool", tier:1, kit:{p:"#C8102E",s:"#FFFFFF",t:"#00B2A9"}, players:[
    ["Alisson", 88, "GK", 33],
    ["Giorgi Mamardashvili", 80, "GK", 25],
    ["Virgil van Dijk", 88, "CB", 34],
    ["Ibrahima Konaté", 85, "CB", 26],
    ["Jeremie Frimpong", 82, "RB/RWB", 24],
    ["Milos Kerkez", 81, "LB/LWB", 21],
    ["Ryan Gravenberch", 86, "CDM/CM", 23],
    ["Alexis Mac Allister", 87, "CM/CAM", 26],
    ["Dominik Szoboszlai", 85, "CM/CAM", 24],
    ["Mohamed Salah", 91, "RW", 33],
    ["Florian Wirtz", 90, "CAM/LW", 22],
    ["Cody Gakpo", 84, "LW/ST", 26],
    ["Alexander Isak", 88, "ST", 25]
  ]},
  { name:"Arsenal", short:"Arsenal", tier:1, kit:{p:"#EF0107",s:"#FFFFFF",t:"#23333F"}, players:[
    ["David Raya", 87, "GK", 30],
    ["Kepa Arrizabalaga", 78, "GK", 31],
    ["William Saliba", 88, "CB", 24],
    ["Gabriel Magalhães", 86, "CB", 28],
    ["Jurriën Timber", 82, "RB/CB", 24],
    ["Riccardo Calafiori", 81, "LB/CB", 23],
    ["Declan Rice", 89, "CDM/CM", 27],
    ["Martín Zubimendi", 85, "CDM/CM", 26],
    ["Martin Ødegaard", 88, "CAM/CM", 27],
    ["Bukayo Saka", 89, "RW", 24],
    ["Eberechi Eze", 84, "CAM/LW", 27],
    ["Gabriel Martinelli", 83, "LW", 24],
    ["Viktor Gyökeres", 87, "ST", 27]
  ]},
  { name:"Manchester City", short:"Man City", tier:1, kit:{p:"#6CABDD",s:"#FFFFFF",t:"#1C2C5B"}, players:[
    ["Gianluigi Donnarumma", 89, "GK", 26],
    ["James Trafford", 78, "GK", 23],
    ["Rúben Dias", 87, "CB", 28],
    ["Joško Gvardiol", 85, "CB/LB", 23],
    ["Nathan Aké", 80, "CB/LB", 30],
    ["Matheus Nunes", 79, "RB/CM", 27],
    ["Rayan Aït-Nouri", 80, "LB/LWB", 24],
    ["Rodri", 90, "CDM", 29],
    ["Tijjani Reijnders", 84, "CM/CAM", 27],
    ["Bernardo Silva", 86, "CM/RW", 31],
    ["Phil Foden", 87, "CAM/LW", 25],
    ["Rayan Cherki", 83, "CAM/RW", 22],
    ["Erling Haaland", 91, "ST", 25]
  ]},
  { name:"Chelsea", short:"Chelsea", tier:2, kit:{p:"#034694",s:"#FFFFFF",t:"#DBA111"}, players:[
    ["Robert Sánchez", 81, "GK", 28],
    ["Filip Jörgensen", 75, "GK", 23],
    ["Levi Colwill", 82, "CB/LB", 22],
    ["Wesley Fofana", 80, "CB", 24],
    ["Trevoh Chalobah", 78, "CB", 26],
    ["Malo Gusto", 80, "RB/RWB", 22],
    ["Marc Cucurella", 82, "LB/LWB", 27],
    ["Moisés Caicedo", 87, "CDM", 24],
    ["Enzo Fernández", 85, "CM/CAM", 24],
    ["Cole Palmer", 89, "CAM", 23],
    ["Pedro Neto", 81, "RW/LW", 25],
    ["Estêvão", 80, "RW/LW", 18],
    ["João Pedro", 82, "ST/CAM", 24]
  ]},
  { name:"Newcastle United", short:"Newcastle", tier:2, kit:{p:"#241F20",s:"#FFFFFF",t:"#41B6E6"}, players:[
    ["Nick Pope", 81, "GK", 33],
    ["Martin Dúbravka", 76, "GK", 36],
    ["Sven Botman", 81, "CB", 25],
    ["Fabian Schär", 80, "CB", 33],
    ["Dan Burn", 77, "CB/LB", 33],
    ["Tino Livramento", 79, "RB/LB", 23],
    ["Lewis Hall", 78, "LB/LWB", 21],
    ["Bruno Guimarães", 86, "CDM/CM", 28],
    ["Sandro Tonali", 84, "CM/CDM", 25],
    ["Joelinton", 82, "CM", 29],
    ["Anthony Gordon", 83, "LW/ST", 24],
    ["Anthony Elanga", 80, "RW/LW", 23],
    ["Nick Woltemade", 80, "ST", 23]
  ]},
  { name:"Manchester United", short:"Man Utd", tier:2, kit:{p:"#DA291C",s:"#FBE122",t:"#000000"}, players:[
    ["Altay Bayındır", 76, "GK", 27],
    ["Senne Lammens", 74, "GK", 23],
    ["Matthijs de Ligt", 82, "CB", 26],
    ["Lisandro Martínez", 82, "CB/LB", 27],
    ["Leny Yoro", 80, "CB", 20],
    ["Noussair Mazraoui", 80, "RB/RWB", 27],
    ["Patrick Dorgu", 76, "LB/LWB", 21],
    ["Casemiro", 80, "CDM", 33],
    ["Manuel Ugarte", 79, "CDM/CM", 24],
    ["Bruno Fernandes", 87, "CAM/CM", 31],
    ["Bryan Mbeumo", 84, "RW/ST", 26],
    ["Matheus Cunha", 84, "ST/CAM", 26],
    ["Benjamin Šeško", 82, "ST", 22]
  ]},
  { name:"Tottenham Hotspur", short:"Tottenham", tier:2, kit:{p:"#FFFFFF",s:"#132257",t:"#132257"}, players:[
    ["Guglielmo Vicario", 83, "GK", 29],
    ["Antonín Kinský", 75, "GK", 22],
    ["Cristian Romero", 85, "CB", 27],
    ["Micky van de Ven", 83, "CB", 24],
    ["Kevin Danso", 77, "CB", 27],
    ["Pedro Porro", 81, "RB/RWB", 26],
    ["Destiny Udogie", 80, "LB/LWB", 23],
    ["João Palhinha", 82, "CDM", 30],
    ["Rodrigo Bentancur", 80, "CM/CDM", 28],
    ["Mohammed Kudus", 84, "RW/CAM", 25],
    ["Xavi Simons", 84, "CAM/LW", 22],
    ["Pape Matar Sarr", 79, "CM", 23],
    ["Dominic Solanke", 81, "ST", 28]
  ]},
  { name:"Aston Villa", short:"Aston Villa", tier:2, kit:{p:"#670E36",s:"#95BFE5",t:"#FFE500"}, players:[
    ["Emiliano Martínez", 85, "GK", 33],
    ["Marco Bizot", 75, "GK", 34],
    ["Pau Torres", 81, "CB", 28],
    ["Ezri Konsa", 80, "CB/RB", 28],
    ["Tyrone Mings", 77, "CB", 32],
    ["Matty Cash", 78, "RB/RWB", 28],
    ["Lucas Digne", 78, "LB", 32],
    ["Boubacar Kamara", 82, "CDM", 26],
    ["Youri Tielemans", 83, "CM/CDM", 28],
    ["John McGinn", 79, "CM", 31],
    ["Morgan Rogers", 82, "CAM/LW", 23],
    ["Emiliano Buendía", 79, "RW/CAM", 29],
    ["Ollie Watkins", 84, "ST", 30]
  ]},
  { name:"Brighton & Hove Albion", short:"Brighton", tier:3, kit:{p:"#0057B8",s:"#FFFFFF",t:"#FFCD00"}, players:[
    ["Bart Verbruggen", 80, "GK", 23],
    ["Jason Steele", 71, "GK", 35],
    ["Lewis Dunk", 78, "CB", 34],
    ["Jan Paul van Hecke", 78, "CB", 25],
    ["Igor Julio", 76, "CB/LB", 27],
    ["Tariq Lamptey", 75, "RB/RWB", 25],
    ["Maxim De Cuyper", 76, "LB/LWB", 25],
    ["Carlos Baleba", 81, "CDM/CM", 21],
    ["Mats Wieffer", 78, "CDM/CM", 25],
    ["Kaoru Mitoma", 83, "LW", 28],
    ["Yankuba Minteh", 80, "RW", 21],
    ["Georginio Rutter", 80, "CAM/ST", 23],
    ["Danny Welbeck", 77, "ST", 35]
  ]},
  { name:"Nottingham Forest", short:"Forest", tier:3, kit:{p:"#DD0000",s:"#FFFFFF",t:"#FFFFFF"}, players:[
    ["Matz Sels", 80, "GK", 33],
    ["Carlos Miguel", 73, "GK", 27],
    ["Murillo", 81, "CB", 23],
    ["Nikola Milenković", 80, "CB", 28],
    ["Morato", 75, "CB", 24],
    ["Ola Aina", 78, "RB/LB", 29],
    ["Neco Williams", 76, "LB/RB", 24],
    ["Elliot Anderson", 80, "CM/CDM", 23],
    ["Ibrahim Sangaré", 77, "CDM", 27],
    ["Morgan Gibbs-White", 82, "CAM", 25],
    ["Dan Ndoye", 79, "RW/LW", 24],
    ["Callum Hudson-Odoi", 78, "LW/RW", 25],
    ["Chris Wood", 80, "ST", 33]
  ]},
  { name:"Crystal Palace", short:"Crystal Palace", tier:3, kit:{p:"#1B458F",s:"#C4122E",t:"#FFFFFF"}, players:[
    ["Dean Henderson", 81, "GK", 28],
    ["Walter Benítez", 73, "GK", 32],
    ["Marc Guéhi", 83, "CB", 25],
    ["Maxence Lacroix", 79, "CB", 25],
    ["Chris Richards", 78, "CB", 25],
    ["Daniel Muñoz", 80, "RB/RWB", 29],
    ["Tyrick Mitchell", 78, "LB/LWB", 26],
    ["Adam Wharton", 80, "CDM/CM", 21],
    ["Will Hughes", 74, "CM", 30],
    ["Daichi Kamada", 79, "CAM/CM", 29],
    ["Ismaïla Sarr", 80, "RW/LW", 27],
    ["Yeremy Pino", 79, "RW/LW", 23],
    ["Jean-Philippe Mateta", 81, "ST", 28]
  ]},
  { name:"AFC Bournemouth", short:"Bournemouth", tier:3, kit:{p:"#DA291C",s:"#000000",t:"#FFFFFF"}, players:[
    ["Đorđe Petrović", 79, "GK", 26],
    ["Will Dennis", 70, "GK", 25],
    ["Marcos Senesi", 79, "CB", 28],
    ["Bafodé Diakité", 78, "CB/RB", 24],
    ["Julián Araujo", 76, "RB/RWB", 24],
    ["Adrien Truffert", 77, "LB/LWB", 23],
    ["Tyler Adams", 78, "CDM", 26],
    ["Lewis Cook", 76, "CM/CDM", 28],
    ["Ryan Christie", 76, "CM/CAM", 30],
    ["Antoine Semenyo", 82, "RW/ST", 25],
    ["Justin Kluivert", 80, "LW/RW", 26],
    ["Marcus Tavernier", 77, "LW/CAM", 26],
    ["Evanilson", 80, "ST", 26]
  ]},
  { name:"Brentford", short:"Brentford", tier:3, kit:{p:"#E30613",s:"#FFFFFF",t:"#FFFFFF"}, players:[
    ["Caoimhín Kelleher", 79, "GK", 27],
    ["Hákon Valdimarsson", 71, "GK", 24],
    ["Nathan Collins", 79, "CB", 24],
    ["Sepp van den Berg", 76, "CB", 24],
    ["Ethan Pinnock", 76, "CB", 32],
    ["Michael Kayode", 75, "RB/RWB", 21],
    ["Rico Henry", 74, "LB/LWB", 28],
    ["Vitaly Janelt", 76, "CDM/CM", 27],
    ["Mathias Jensen", 76, "CM", 29],
    ["Mikkel Damsgaard", 80, "CAM", 25],
    ["Kevin Schade", 78, "RW/LW", 24],
    ["Dango Ouattara", 78, "RW/LW", 23],
    ["Igor Thiago", 78, "ST", 24]
  ]},
  { name:"Fulham", short:"Fulham", tier:3, kit:{p:"#FFFFFF",s:"#000000",t:"#000000"}, players:[
    ["Bernd Leno", 81, "GK", 33],
    ["Benjamin Lecomte", 72, "GK", 34],
    ["Joachim Andersen", 80, "CB", 29],
    ["Calvin Bassey", 79, "CB/LB", 25],
    ["Issa Diop", 75, "CB", 28],
    ["Kenny Tete", 76, "RB", 29],
    ["Antonee Robinson", 80, "LB/LWB", 28],
    ["Sander Berge", 78, "CM/CDM", 27],
    ["Emile Smith Rowe", 78, "CAM/CM", 25],
    ["Alex Iwobi", 79, "RW/CAM", 29],
    ["Harry Wilson", 77, "RW/LW", 28],
    ["Rodrigo Muniz", 78, "ST", 24],
    ["Raúl Jiménez", 78, "ST", 34]
  ]},
  { name:"Everton", short:"Everton", tier:3, kit:{p:"#003399",s:"#FFFFFF",t:"#FFFFFF"}, players:[
    ["Jordan Pickford", 84, "GK", 31],
    ["Mark Travers", 72, "GK", 26],
    ["Jarrad Branthwaite", 82, "CB", 23],
    ["James Tarkowski", 78, "CB", 32],
    ["Jake O'Brien", 75, "RB/CB", 24],
    ["Vitalii Mykolenko", 77, "LB", 26],
    ["Idrissa Gueye", 77, "CDM", 36],
    ["Carlos Alcaraz", 77, "CM/CAM", 23],
    ["James Garner", 75, "CM", 24],
    ["Iliman Ndiaye", 80, "LW/CAM", 25],
    ["Jack Grealish", 80, "LW/RW", 30],
    ["Dwight McNeil", 78, "LW/CAM", 26],
    ["Beto", 76, "ST", 27]
  ]},
  { name:"West Ham United", short:"West Ham", tier:3, kit:{p:"#7A263A",s:"#1BB1E7",t:"#FFFFFF"}, players:[
    ["Alphonse Areola", 80, "GK", 32],
    ["Mads Hermansen", 76, "GK", 25],
    ["Jean-Clair Todibo", 79, "CB", 25],
    ["Max Kilman", 78, "CB", 28],
    ["Konstantinos Mavropanos", 76, "CB", 27],
    ["Aaron Wan-Bissaka", 79, "RB/RWB", 27],
    ["El Hadji Malick Diouf", 75, "LB/LWB", 20],
    ["Tomáš Souček", 78, "CM", 30],
    ["Edson Álvarez", 78, "CDM", 27],
    ["Lucas Paquetá", 82, "CAM/CM", 28],
    ["Jarrod Bowen", 82, "RW/ST", 28],
    ["Crysencio Summerville", 78, "LW/RW", 23],
    ["Niclas Füllkrug", 78, "ST", 32]
  ]},
  { name:"Wolverhampton", short:"Wolves", tier:4, kit:{p:"#FDB913",s:"#231F20",t:"#231F20"}, players:[
    ["José Sá", 78, "GK", 32],
    ["Sam Johnstone", 74, "GK", 32],
    ["Toti Gomes", 75, "CB", 26],
    ["Santiago Bueno", 74, "CB", 26],
    ["Yerson Mosquera", 73, "CB", 24],
    ["Matt Doherty", 73, "RB/RWB", 33],
    ["Hugo Bueno", 72, "LB/LWB", 23],
    ["João Gomes", 78, "CDM/CM", 24],
    ["Marshall Munetsi", 74, "CM", 29],
    ["Jhon Arias", 77, "RW/CAM", 27],
    ["Hwang Hee-chan", 75, "RW/ST", 29],
    ["Rodrigo Gomes", 74, "RW/RWB", 22],
    ["Jørgen Strand Larsen", 77, "ST", 25]
  ]},
  { name:"Burnley", short:"Burnley", tier:4, kit:{p:"#6C1D45",s:"#99D6EA",t:"#FFFFFF"}, players:[
    ["Max Weiß", 71, "GK", 21],
    ["Václav Hladký", 70, "GK", 34],
    ["Maxime Estève", 74, "CB", 23],
    ["Joe Worrall", 72, "CB", 28],
    ["Hjalmar Ekdal", 71, "CB", 26],
    ["Connor Roberts", 72, "RB", 30],
    ["Quilindschy Hartman", 72, "LB/LWB", 23],
    ["Josh Cullen", 74, "CM/CDM", 29],
    ["Josh Brownhill", 74, "CM/CAM", 29],
    ["Lesley Ugochukwu", 74, "CDM/CM", 21],
    ["Jaidon Anthony", 72, "LW/RW", 25],
    ["Zian Flemming", 73, "CAM/ST", 27],
    ["Lyle Foster", 73, "ST", 25]
  ]},
  { name:"Leeds United", short:"Leeds", tier:4, kit:{p:"#FFFFFF",s:"#1D428A",t:"#FFCD00"}, players:[
    ["Illan Meslier", 75, "GK", 25],
    ["Lucas Perri", 75, "GK", 27],
    ["Pascal Struijk", 76, "CB/LB", 26],
    ["Joe Rodon", 75, "CB", 28],
    ["Jaka Bijol", 75, "CB", 26],
    ["Jayden Bogle", 75, "RB/RWB", 25],
    ["Gabriel Gudmundsson", 73, "LB/LWB", 26],
    ["Ethan Ampadu", 77, "CDM/CB", 25],
    ["Ao Tanaka", 75, "CM/CDM", 27],
    ["Anton Stach", 75, "CM", 26],
    ["Daniel James", 76, "RW/LW", 28],
    ["Joël Piroe", 75, "ST/CAM", 25],
    ["Brenden Aaronson", 74, "CAM/RW", 25]
  ]},
  { name:"Sunderland", short:"Sunderland", tier:4, kit:{p:"#EB172B",s:"#FFFFFF",t:"#211E1F"}, players:[
    ["Robin Roefs", 72, "GK", 22],
    ["Anthony Patterson", 72, "GK", 25],
    ["Dan Ballard", 73, "CB", 25],
    ["Nordi Mukiele", 75, "CB/RB", 27],
    ["Omar Alderete", 73, "CB/LB", 28],
    ["Trai Hume", 73, "RB/RWB", 23],
    ["Reinildo Mandava", 74, "LB", 31],
    ["Granit Xhaka", 80, "CM/CDM", 33],
    ["Enzo Le Fée", 77, "CAM/CM", 25],
    ["Habib Diarra", 75, "CM/CAM", 21],
    ["Simon Adingra", 76, "RW/LW", 23],
    ["Brian Brobbey", 75, "ST", 23],
    ["Wilson Isidor", 74, "ST", 25]
  ]}
];
