window.CLUBS_FRA = [
  { name:"Paris Saint-Germain", short:"PSG", tier:1, kit:{p:"#004170",s:"#DA291C",t:"#FFFFFF"}, players:[
    ["Lucas Chevalier", 84, "GK", 23],
    ["Matvey Safonov", 78, "GK", 26],
    ["Marquinhos", 86, "CB", 31],
    ["Willian Pacho", 85, "CB", 23],
    ["Illia Zabarnyi", 83, "CB", 22],
    ["Achraf Hakimi", 91, "RB/RWB", 26],
    ["Nuno Mendes", 89, "LB/LWB", 23],
    ["Vitinha", 91, "CM/CDM", 25],
    ["João Neves", 89, "CM/CDM", 20],
    ["Désiré Doué", 87, "CAM/RW", 20],
    ["Ousmane Dembélé", 93, "RW/ST", 28],
    ["Khvicha Kvaratskhelia", 89, "LW/RW", 24],
    ["Gonçalo Ramos", 83, "ST", 24]
  ]},
  { name:"Marseille", short:"OM", tier:2, kit:{p:"#FFFFFF",s:"#2FAEE0",t:"#009DDC"}, players:[
    ["Gerónimo Rulli", 81, "GK", 33],
    ["Jeffrey de Lange", 74, "GK", 28],
    ["Leonardo Balerdi", 81, "CB", 26],
    ["Benjamin Pavard", 82, "CB/RB", 29],
    ["Nayef Aguerd", 79, "CB", 29],
    ["Timothy Weah", 78, "RB/RW", 25],
    ["Facundo Medina", 79, "LB/CB", 26],
    ["Pierre-Emile Højbjerg", 82, "CDM/CM", 30],
    ["Matt O'Riley", 76, "CM/CAM", 24],
    ["Angel Gomes", 78, "CM/CAM", 24],
    ["Mason Greenwood", 84, "RW/ST", 23],
    ["Igor Paixão", 79, "LW/RW", 25],
    ["Pierre-Emerick Aubameyang", 80, "ST", 36]
  ]},
  { name:"Monaco", short:"MON", tier:2, kit:{p:"#E63B43",s:"#FFFFFF",t:"#FFFFFF"}, players:[
    ["Lukas Hradecky", 79, "GK", 35],
    ["Philipp Köhn", 74, "GK", 27],
    ["Thilo Kehrer", 78, "CB", 28],
    ["Eric Dier", 78, "CB", 31],
    ["Mohammed Salisu", 76, "CB", 26],
    ["Vanderson", 80, "RB/RWB", 24],
    ["Caio Henrique", 80, "LB/LWB", 28],
    ["Denis Zakaria", 82, "CDM/CM", 28],
    ["Aleksandr Golovin", 82, "CAM/CM", 29],
    ["Lamine Camara", 79, "CM/CDM", 21],
    ["Maghnes Akliouche", 83, "RW/CAM", 23],
    ["Ansu Fati", 78, "LW/ST", 22],
    ["Folarin Balogun", 79, "ST", 24]
  ]},
  { name:"Lille", short:"LIL", tier:2, kit:{p:"#E01E13",s:"#1F2A44",t:"#FFFFFF"}, players:[
    ["Berke Özer", 79, "GK", 25],
    ["Arnaud Bodart", 73, "GK", 27],
    ["Alexsandro", 82, "CB", 26],
    ["Chancel Mbemba", 79, "CB", 31],
    ["Aïssa Mandi", 75, "CB", 34],
    ["Thomas Meunier", 78, "RB/RWB", 33],
    ["Romain Perraud", 78, "LB", 27],
    ["Benjamin André", 80, "CDM/CM", 35],
    ["Ayyoub Bouaddi", 80, "CM/CDM", 18],
    ["Hákon Haraldsson", 81, "CAM/CM", 22],
    ["Osame Sahraoui", 79, "LW/RW", 24],
    ["Matias Fernandez-Pardo", 77, "LW/ST", 20],
    ["Olivier Giroud", 79, "ST", 38]
  ]},
  { name:"Lyon", short:"OL", tier:2, kit:{p:"#FFFFFF",s:"#DA291C",t:"#1B458F"}, players:[
    ["Dominik Greif", 79, "GK", 28],
    ["Rémy Descamps", 72, "GK", 29],
    ["Moussa Niakhaté", 80, "CB", 29],
    ["Clinton Mata", 78, "CB/RB", 32],
    ["Ruben Kluivert", 74, "CB", 24],
    ["Ainsley Maitland-Niles", 78, "RB/RWB", 27],
    ["Nicolás Tagliafico", 80, "LB", 32],
    ["Corentin Tolisso", 81, "CM/CAM", 31],
    ["Tanner Tessmann", 77, "CDM/CM", 23],
    ["Pavel Šulc", 79, "CAM/ST", 24],
    ["Malick Fofana", 81, "LW/RW", 20],
    ["Adam Karabec", 76, "RW/CAM", 22],
    ["Endrick", 82, "ST", 19]
  ]},
  { name:"Nice", short:"NIC", tier:3, kit:{p:"#C8102E",s:"#000000",t:"#FFFFFF"}, players:[
    ["Yehvann Diouf", 77, "GK", 25],
    ["Teddy Boulhendi", 70, "GK", 24],
    ["Moïse Bombito", 76, "CB", 25],
    ["Mohamed Abdelmonem", 75, "CB", 26],
    ["Juma Bah", 73, "CB", 18],
    ["Jonathan Clauss", 78, "RWB/RB", 32],
    ["Melvin Bard", 77, "LB/LWB", 24],
    ["Hicham Boudaoui", 76, "CM/CDM", 25],
    ["Pablo Rosario", 74, "CDM", 28],
    ["Sofiane Diop", 78, "CAM/LW", 25],
    ["Jérémie Boga", 77, "LW/RW", 28],
    ["Mohamed-Ali Cho", 76, "RW/ST", 21],
    ["Terem Moffi", 78, "ST", 26]
  ]},
  { name:"Lens", short:"Lens", tier:3, kit:{p:"#FFE000",s:"#E2231A",t:"#000000"}, players:[
    ["Hervé Koffi", 75, "GK", 28],
    ["Robin Risser", 71, "GK", 21],
    ["Jonathan Gradit", 74, "CB", 32],
    ["Malang Sarr", 73, "CB", 26],
    ["Ruben Aguilar", 72, "RB/CB", 32],
    ["Deiver Machado", 73, "LB/LWB", 32],
    ["Jhoanner Chávez", 72, "LB/RB", 23],
    ["Neil El Aynaoui", 76, "CM/CDM", 24],
    ["Adrien Thomasson", 75, "CM/CAM", 31],
    ["Andy Diouf", 75, "CDM/CM", 22],
    ["Florian Sotoca", 76, "RW/ST", 30],
    ["Wesley Saïd", 73, "LW/RW", 30],
    ["Rayan Fofana", 72, "ST", 20]
  ]},
  { name:"Rennes", short:"Rennes", tier:3, kit:{p:"#E51B22",s:"#000000",t:"#000000"}, players:[
    ["Brice Samba", 80, "GK", 31],
    ["Gauthier Gallon", 71, "GK", 32],
    ["Christopher Wooh", 76, "CB", 24],
    ["Anthony Rouault", 73, "CB", 24],
    ["Jérémy Jacquet", 73, "CB", 20],
    ["Hans Hateboer", 72, "RB/RWB", 31],
    ["Quentin Merlin", 75, "LB/LWB", 23],
    ["Valentin Rongier", 77, "CM/CDM", 31],
    ["Djaoui Cissé", 73, "CDM/CM", 21],
    ["Ludovic Blas", 78, "CAM/RW", 27],
    ["Breel Embolo", 78, "ST", 28],
    ["Esteban Lepaul", 75, "ST/LW", 25],
    ["Kader Meïté", 72, "RW/ST", 20]
  ]},
  { name:"Strasbourg", short:"Strasbourg", tier:3, kit:{p:"#0091D2",s:"#FFFFFF",t:"#E2231A"}, players:[
    ["Mike Penders", 74, "GK", 20],
    ["Alaa Bellaarouch", 70, "GK", 21],
    ["Mamadou Sarr", 73, "CB", 20],
    ["Saïdou Sow", 72, "CB", 23],
    ["Marvin Senaya", 72, "RB/RWB", 23],
    ["Caleb Wiley", 72, "LB/LWB", 20],
    ["Valentin Barco", 74, "LB/LWB", 21],
    ["Ismaël Doukouré", 73, "CDM/CM", 22],
    ["Andrey Santos", 77, "CM/CDM", 21],
    ["Dilane Bakwa", 76, "RW/CAM", 22],
    ["Sebastian Nanasi", 73, "LW/CAM", 23],
    ["Emanuel Emegha", 77, "ST", 22],
    ["Joaquín Panichelli", 75, "ST", 23]
  ]},
  { name:"Nantes", short:"Nantes", tier:4, kit:{p:"#FCD400",s:"#009639",t:"#009639"}, players:[
    ["Anthony Lopes", 76, "GK", 35],
    ["Patrik Carlgren", 69, "GK", 33],
    ["Jean-Charles Castelletto", 73, "CB", 30],
    ["Chidozie Awaziem", 72, "CB", 28],
    ["Nicolas Cozza", 72, "CB/LB", 26],
    ["Tylel Tati", 71, "CB", 18],
    ["Johann Lepenant", 73, "CM/CDM", 22],
    ["Junior Mwanga", 72, "CDM/CM", 22],
    ["Louis Leroux", 70, "CM", 20],
    ["Matthis Abline", 75, "RW/ST", 22],
    ["Herba Guirassy", 70, "RW", 21],
    ["Mostafa Mohamed", 75, "ST", 27],
    ["Youssef El-Arabi", 73, "ST", 38]
  ]},
  { name:"Toulouse", short:"Toulouse", tier:4, kit:{p:"#5F259F",s:"#FFFFFF",t:"#FFFFFF"}, players:[
    ["Guillaume Restes", 76, "GK", 20],
    ["Jordan Gaspar", 69, "GK", 25],
    ["Charlie Cresswell", 75, "CB", 23],
    ["Rasmus Nicolaisen", 72, "CB", 28],
    ["Kévin Keben", 71, "CB", 22],
    ["Warren Kamanzi", 72, "RB/RWB", 24],
    ["Moussa Diarra", 71, "LB/CB", 24],
    ["Vincent Sierro", 75, "CM/CAM", 30],
    ["Stijn Spierings", 72, "CM/CDM", 29],
    ["Cristian Cásseres", 73, "CM/CDM", 25],
    ["Aron Dønnum", 73, "RW/LM", 27],
    ["Yann Gboho", 74, "LW/CAM", 24],
    ["Frank Magri", 73, "ST/RW", 26]
  ]},
  { name:"Brest", short:"Brest", tier:4, kit:{p:"#E2231A",s:"#FFFFFF",t:"#1A2B4A"}, players:[
    ["Grégoire Coudert", 72, "GK", 26],
    ["Radek Vítek", 68, "GK", 21],
    ["Brendan Chardonnet", 73, "CB", 30],
    ["Lilian Brassier", 73, "CB", 25],
    ["Kenny Lala", 72, "RB/RWB", 33],
    ["Bradley Locko", 73, "LB/LWB", 23],
    ["Pierre Lees-Melou", 75, "CM/CDM", 32],
    ["Hugo Magnetti", 72, "CDM/CM", 27],
    ["Kamory Doumbia", 72, "CM/CAM", 22],
    ["Romain Del Castillo", 75, "CAM/RW", 29],
    ["Abdallah Sima", 74, "RW/ST", 24],
    ["Jeremy Le Douaron", 72, "LW/ST", 27],
    ["Ludovic Ajorque", 76, "ST", 31]
  ]},
  { name:"Auxerre", short:"Auxerre", tier:4, kit:{p:"#0069B4",s:"#FFFFFF",t:"#FFFFFF"}, players:[
    ["Donovan Léon", 72, "GK", 32],
    ["Théo De Percin", 68, "GK", 22],
    ["Jubal", 71, "CB", 31],
    ["Clément Akpa", 70, "CB", 23],
    ["Paul Joly", 71, "RB/RWB", 26],
    ["Marquinhos Cipriano", 72, "LB/LWB", 26],
    ["Rúben Vinagre", 71, "LB/LWB", 26],
    ["Lasso Coulibaly", 71, "CDM/CM", 22],
    ["Hamed Junior Traorè", 74, "CAM/CM", 25],
    ["Gauthier Hein", 73, "RW/CAM", 28],
    ["Lassine Sinayoko", 73, "LW/ST", 25],
    ["Sékou Mara", 73, "ST", 23],
    ["Ado Onaiwu", 70, "ST", 30]
  ]},
  { name:"Le Havre", short:"Le Havre", tier:4, kit:{p:"#5BC2E7",s:"#1A2B4A",t:"#1A2B4A"}, players:[
    ["Mory Diaw", 73, "GK", 31],
    ["Arthur Desmas", 69, "GK", 31],
    ["Arouna Sangante", 72, "CB", 23],
    ["Etienne Youte Kinkoue", 71, "CB", 23],
    ["Yoann Salmier", 70, "CB", 32],
    ["Gautier Lloris", 70, "RB/RWB", 27],
    ["Christopher Opéri", 71, "LB/LWB", 28],
    ["Abdoulaye Touré", 73, "CDM/CM", 31],
    ["Daler Kuzyaev", 73, "CM/CDM", 32],
    ["Félix Lemaréchal", 72, "CAM/CM", 20],
    ["Rassoul Ndiaye", 71, "CM", 24],
    ["Issa Soumaré", 71, "RW/LW", 23],
    ["Steve Ngoura", 70, "ST/RW", 21]
  ]},
  { name:"Angers", short:"Angers", tier:4, kit:{p:"#000000",s:"#FFFFFF",t:"#FFFFFF"}, players:[
    ["Yahia Fofana", 73, "GK", 24],
    ["Paul Bernardoni", 72, "GK", 28],
    ["Jordan Lefort", 70, "CB", 28],
    ["Lilian Raolisoa", 70, "CB", 22],
    ["Yann Valery", 71, "RB/RWB", 28],
    ["Ali Abdi", 71, "LB/LWB", 31],
    ["Jean-Eudes Aholou", 72, "CDM/CM", 31],
    ["Himad Abdelli", 75, "CAM/CM", 26],
    ["Marius Courcoul", 69, "CM/CDM", 21],
    ["Jim Allevinah", 71, "RW/LW", 30],
    ["Bamba Dieng", 72, "ST/LW", 25],
    ["Sidiki Chérif", 70, "ST", 22],
    ["Amine Salama", 71, "ST", 25]
  ]},
  { name:"Metz", short:"Metz", tier:4, kit:{p:"#7C0A20",s:"#FFFFFF",t:"#FFFFFF"}, players:[
    ["Jonathan Fischer", 71, "GK", 23],
    ["Arthur Sukhov", 66, "GK", 19],
    ["Matthieu Udol", 72, "LB/CB", 29],
    ["Sadibou Sané", 70, "CB", 26],
    ["Fali Candé", 70, "CB", 27],
    ["Koffi Kouao", 70, "RB/LB", 24],
    ["Arthur Atta", 73, "CM/CDM", 22],
    ["Kévin N'Doram", 71, "CDM/CM", 29],
    ["Danley Jean Jacques", 70, "CM/CDM", 25],
    ["Joël Asoro", 71, "RW/ST", 26],
    ["Cheikh Sabaly", 70, "LW/RW", 24],
    ["Pablo Pagis", 71, "ST/RW", 26],
    ["Habib Diallo", 75, "ST", 30]
  ]},
  { name:"Lorient", short:"Lorient", tier:4, kit:{p:"#F18A00",s:"#000000",t:"#000000"}, players:[
    ["Yvon Mvogo", 73, "GK", 31],
    ["Paul Nardi", 68, "GK", 31],
    ["Montassar Talbi", 73, "CB", 27],
    ["Igor Silva", 70, "CB", 24],
    ["Arsène Kouassi", 69, "CB", 22],
    ["Nathaniel Adjei", 70, "RB/CB", 22],
    ["Vincent Le Goff", 71, "LB/LWB", 35],
    ["Laurent Abergel", 73, "CDM/CM", 32],
    ["Tom Lacoux", 70, "CM/CDM", 22],
    ["Théo Le Bris", 72, "RW/CAM", 23],
    ["Aiyegun Tosin", 73, "ST/RW", 27],
    ["Sambou Soumano", 71, "LW/ST", 25],
    ["Mohamed Bamba", 71, "ST", 24]
  ]},
  { name:"Paris FC", short:"Paris FC", tier:4, kit:{p:"#003C7D",s:"#E2231A",t:"#FFFFFF"}, players:[
    ["Kévin Trapp", 76, "GK", 35],
    ["Obed Nkambadio", 72, "GK", 22],
    ["Otávio", 71, "CB", 29],
    ["Thibault De Smet", 71, "CB/LB", 27],
    ["Sergio Akieme", 71, "LB/LWB", 28],
    ["Maxime Lopez", 75, "CM/CDM", 27],
    ["Mahamadou Sangaré", 71, "CDM/CM", 23],
    ["Vincent Marchetti", 72, "CM/CAM", 24],
    ["Adama Camara", 70, "CDM", 23],
    ["Ilan Kebbal", 74, "CAM/RW", 26],
    ["Moses Simon", 75, "LW/RW", 30],
    ["Jean-Philippe Krasso", 73, "ST", 28],
    ["Willem Geubbels", 72, "ST", 24]
  ]}
];
