/* ELF '26 — Bundesliga 2025/26 club squads (summer 2025 transfers applied).
   [name, rating, positions("/"-sep, primary first), age]. Aggressive 2025/26 scale. */
window.CLUBS_BUN = [
  { name:"FC Bayern München", short:"Bayern", tier:1, kit:{p:"#DC052D",s:"#FFFFFF",t:"#FFFFFF"}, players:[
    ["Manuel Neuer", 86, "GK", 39],
    ["Jonas Urbig", 77, "GK", 22],
    ["Dayot Upamecano", 86, "CB", 27],
    ["Jonathan Tah", 86, "CB", 29],
    ["Min-jae Kim", 84, "CB", 29],
    ["Konrad Laimer", 84, "RB/CM", 28],
    ["Alphonso Davies", 86, "LB/LWB", 25],
    ["Joshua Kimmich", 88, "CDM/CM", 30],
    ["Aleksandar Pavlović", 82, "CM/CDM", 21],
    ["Jamal Musiala", 92, "CAM", 22],
    ["Michael Olise", 89, "RW/CAM", 23],
    ["Luis Díaz", 87, "LW/ST", 28],
    ["Harry Kane", 91, "ST", 32]
  ]},
  { name:"Bayer 04 Leverkusen", short:"Leverkusen", tier:2, kit:{p:"#000000",s:"#E32221",t:"#E32221"}, players:[
    ["Mark Flekken", 82, "GK", 32],
    ["Niklas Lomb", 72, "GK", 32],
    ["Edmond Tapsoba", 82, "CB", 26],
    ["Loïc Badé", 81, "CB", 25],
    ["Jarell Quansah", 79, "CB", 22],
    ["Arthur", 75, "RB", 22],
    ["Alejandro Grimaldo", 84, "LB/LWB", 30],
    ["Robert Andrich", 80, "CDM", 31],
    ["Exequiel Palacios", 82, "CM/CDM", 27],
    ["Malik Tillman", 81, "CAM", 23],
    ["Nathan Tella", 77, "RW/LW", 26],
    ["Eliesse Ben Seghir", 78, "LW/CAM", 20],
    ["Patrik Schick", 84, "ST", 29]
  ]},
  { name:"Borussia Dortmund", short:"Dortmund", tier:2, kit:{p:"#FDE100",s:"#000000",t:"#000000"}, players:[
    ["Gregor Kobel", 87, "GK", 27],
    ["Alexander Meyer", 73, "GK", 34],
    ["Nico Schlotterbeck", 85, "CB", 25],
    ["Waldemar Anton", 80, "CB", 29],
    ["Niklas Süle", 79, "CB", 30],
    ["Yan Couto", 77, "RB/RWB", 23],
    ["Ramy Bensebaini", 79, "LB/CB", 30],
    ["Felix Nmecha", 80, "CM/CDM", 25],
    ["Jobe Bellingham", 76, "CM/CAM", 20],
    ["Julian Brandt", 82, "CAM/CM", 29],
    ["Karim Adeyemi", 82, "LW/RW", 23],
    ["Maximilian Beier", 79, "RW/ST", 23],
    ["Serhou Guirassy", 85, "ST", 29]
  ]},
  { name:"RB Leipzig", short:"Leipzig", tier:2, kit:{p:"#FFFFFF",s:"#DD0741",t:"#DD0741"}, players:[
    ["Péter Gulácsi", 80, "GK", 35],
    ["Maarten Vandevoordt", 75, "GK", 23],
    ["Willi Orbán", 82, "CB", 33],
    ["Castello Lukeba", 83, "CB", 23],
    ["El Chadaille Bitshiabu", 75, "CB", 20],
    ["Ridle Baku", 76, "RB", 27],
    ["David Raum", 83, "LB/LWB", 27],
    ["Arthur Vermeeren", 78, "CDM/CM", 20],
    ["Assan Ouédraogo", 77, "CM/CAM", 19],
    ["Christoph Baumgartner", 81, "CAM/ST", 26],
    ["Johan Bakayoko", 81, "RW", 22],
    ["Antonio Nusa", 80, "LW", 20],
    ["Romulo", 79, "ST", 23]
  ]},
  { name:"Eintracht Frankfurt", short:"Frankfurt", tier:2, kit:{p:"#000000",s:"#E1000F",t:"#FFFFFF"}, players:[
    ["Michael Zetterer", 79, "GK", 30],
    ["Kauã Santos", 75, "GK", 22],
    ["Robin Koch", 82, "CB", 29],
    ["Arthur Theate", 81, "CB", 25],
    ["Nnamdi Collins", 76, "CB/RB", 22],
    ["Rasmus Kristensen", 79, "RB/RWB", 28],
    ["Nathaniel Brown", 79, "LB/LWB", 22],
    ["Ellyes Skhiri", 79, "CDM/CM", 30],
    ["Hugo Larsson", 81, "CM", 21],
    ["Can Uzun", 80, "CAM", 20],
    ["Ritsu Doan", 82, "RW", 27],
    ["Jean-Mattéo Bahoya", 75, "LW", 20],
    ["Jonathan Burkardt", 82, "ST", 25]
  ]},
  { name:"VfB Stuttgart", short:"Stuttgart", tier:3, kit:{p:"#FFFFFF",s:"#E32219",t:"#E32219"}, players:[
    ["Alexander Nübel", 81, "GK", 29],
    ["Fabian Bredlow", 73, "GK", 30],
    ["Jeff Chabot", 79, "CB", 27],
    ["Dan-Axel Zagadou", 76, "CB", 26],
    ["Finn Jeltsch", 75, "CB", 19],
    ["Josha Vagnoman", 75, "RB/RWB", 25],
    ["Maximilian Mittelstädt", 80, "LB", 28],
    ["Atakan Karazor", 77, "CDM", 29],
    ["Angelo Stiller", 82, "CM/CDM", 24],
    ["Chema Andrés", 74, "CDM/CM", 20],
    ["Jamie Leweling", 78, "RW", 24],
    ["Tiago Tomás", 76, "LW/ST", 23],
    ["Deniz Undav", 82, "ST/CAM", 29]
  ]},
  { name:"SC Freiburg", short:"Freiburg", tier:3, kit:{p:"#D4001F",s:"#000000",t:"#FFFFFF"}, players:[
    ["Noah Atubolu", 80, "GK", 23],
    ["Florian Müller", 73, "GK", 28],
    ["Matthias Ginter", 79, "CB", 32],
    ["Philipp Lienhart", 79, "CB", 29],
    ["Max Rosenfelder", 74, "CB", 22],
    ["Lukas Kübler", 75, "RB", 33],
    ["Christian Günter", 76, "LB", 33],
    ["Maximilian Eggestein", 77, "CM/CDM", 29],
    ["Patrick Osterhage", 75, "CM/CDM", 25],
    ["Johan Manzambi", 77, "CAM/CM", 20],
    ["Vincenzo Grifo", 78, "LW/CAM", 32],
    ["Yuito Suzuki", 76, "LW/ST", 24],
    ["Igor Matanović", 75, "ST", 23]
  ]},
  { name:"Borussia Mönchengladbach", short:"Gladbach", tier:3, kit:{p:"#FFFFFF",s:"#009A3D",t:"#000000"}, players:[
    ["Moritz Nicolas", 77, "GK", 28],
    ["Jonas Omlin", 73, "GK", 32],
    ["Nico Elvedi", 77, "CB", 29],
    ["Marvin Friedrich", 74, "CB", 30],
    ["Kevin Diks", 76, "CB/RB", 29],
    ["Joe Scally", 75, "RB", 23],
    ["Lukas Ullrich", 72, "LB", 21],
    ["Rocco Reitz", 78, "CDM/CM", 23],
    ["Philipp Sander", 74, "CM", 28],
    ["Kevin Stöger", 75, "CAM/CM", 32],
    ["Franck Honorat", 78, "RW", 29],
    ["Robin Hack", 76, "LW/ST", 27],
    ["Tim Kleindienst", 80, "ST", 30]
  ]},
  { name:"VfL Wolfsburg", short:"Wolfsburg", tier:3, kit:{p:"#65B32E",s:"#FFFFFF",t:"#FFFFFF"}, players:[
    ["Kamil Grabara", 78, "GK", 27],
    ["Marius Müller", 72, "GK", 32],
    ["Moritz Jenz", 75, "CB", 26],
    ["Konstantinos Koulierakis", 77, "CB", 22],
    ["Denis Vavro", 74, "CB", 29],
    ["Kilian Fischer", 74, "RB", 25],
    ["Joakim Mæhle", 77, "LB/RB", 28],
    ["Maximilian Arnold", 78, "CDM/CM", 31],
    ["Vinicius Souza", 75, "CDM", 26],
    ["Christian Eriksen", 78, "CM/CAM", 33],
    ["Patrick Wimmer", 76, "RW/LW", 24],
    ["Mohammed Amoura", 79, "LW/ST", 25],
    ["Jonas Wind", 77, "ST", 26]
  ]},
  { name:"SV Werder Bremen", short:"Bremen", tier:3, kit:{p:"#1D9053",s:"#FFFFFF",t:"#FFFFFF"}, players:[
    ["Mio Backhaus", 75, "GK", 21],
    ["Karl Hein", 71, "GK", 23],
    ["Marco Friedl", 78, "CB", 27],
    ["Amos Pieper", 74, "CB", 28],
    ["Niklas Stark", 75, "CB", 30],
    ["Mitchell Weiser", 78, "RB/RWB", 31],
    ["Felix Agu", 74, "LB/RB", 26],
    ["Jens Stage", 77, "CM", 29],
    ["Karim Coulibaly", 74, "CM/CDM", 18],
    ["Romano Schmid", 78, "CAM", 26],
    ["Samuel Mbangula", 76, "LW/RW", 21],
    ["Marco Grüll", 75, "LW/ST", 27],
    ["Justin Njinmah", 76, "ST", 25]
  ]},
  { name:"TSG Hoffenheim", short:"Hoffenheim", tier:3, kit:{p:"#1961B5",s:"#FFFFFF",t:"#FFFFFF"}, players:[
    ["Oliver Baumann", 79, "GK", 35],
    ["Luca Philipp", 70, "GK", 24],
    ["Robin Hranáč", 76, "CB", 25],
    ["Albian Hajdari", 75, "CB", 22],
    ["Ozan Kabak", 74, "CB", 25],
    ["Vladimír Coufal", 75, "RB", 33],
    ["Alexander Prass", 76, "LB/LWB", 24],
    ["Leon Avdullahu", 76, "CDM", 21],
    ["Grischa Prömel", 75, "CM", 30],
    ["Andrej Kramarić", 79, "CAM/ST", 34],
    ["Bazoumana Touré", 74, "RW/LW", 19],
    ["Tim Lemperle", 75, "LW/ST", 23],
    ["Fisnik Asllani", 78, "ST", 23]
  ]},
  { name:"1. FSV Mainz 05", short:"Mainz", tier:3, kit:{p:"#E2001A",s:"#FFFFFF",t:"#FFFFFF"}, players:[
    ["Robin Zentner", 78, "GK", 31],
    ["Lasse Rieß", 71, "GK", 24],
    ["Andreas Hanche-Olsen", 76, "CB", 28],
    ["Dominik Kohr", 75, "CB/CDM", 31],
    ["Maxim Leitsch", 73, "CB", 27],
    ["Phillipp Mwene", 75, "RB/LB", 31],
    ["Anthony Caci", 76, "LB/RB", 28],
    ["Kaishu Sano", 78, "CDM", 24],
    ["Nadiem Amiri", 78, "CM/CAM", 29],
    ["Sota Kawasaki", 73, "CM", 24],
    ["Paul Nebel", 77, "RW/LW", 23],
    ["Benedict Hollerbach", 76, "LW/ST", 24],
    ["Nelson Weiper", 74, "ST", 20]
  ]},
  { name:"1. FC Union Berlin", short:"Union", tier:4, kit:{p:"#EB1923",s:"#FFFFFF",t:"#FFFFFF"}, players:[
    ["Frederik Rønnow", 76, "GK", 33],
    ["Matheo Raab", 70, "GK", 26],
    ["Diogo Leite", 75, "CB", 26],
    ["Danilho Doekhi", 75, "CB", 27],
    ["Leopold Querfeld", 73, "CB", 21],
    ["Josip Juranović", 75, "RB/RWB", 30],
    ["Tom Rothe", 73, "LWB/LB", 21],
    ["Rani Khedira", 73, "CDM", 31],
    ["András Schäfer", 73, "CM", 26],
    ["Aljoscha Kemlein", 70, "CM/CDM", 21],
    ["Ilyas Ansah", 72, "RW/ST", 20],
    ["Tim Skarke", 70, "LW/RM", 29],
    ["Oliver Burke", 73, "ST", 28]
  ]},
  { name:"FC Augsburg", short:"Augsburg", tier:4, kit:{p:"#FFFFFF",s:"#E30613",t:"#046A38"}, players:[
    ["Finn Dahmen", 75, "GK", 28],
    ["Nediljko Labrović", 71, "GK", 26],
    ["Keven Schlotterbeck", 73, "CB", 28],
    ["Chrislain Matsima", 73, "CB", 23],
    ["Noahkai Banks", 70, "CB", 19],
    ["Marius Wolf", 73, "RB/RM", 30],
    ["Dimitrios Giannoulis", 72, "LB/LWB", 30],
    ["Kristijan Jakić", 73, "CDM/CM", 28],
    ["Elvis Rexhbeçaj", 73, "CM", 28],
    ["Fabian Rieder", 74, "CAM/CM", 23],
    ["Anton Kade", 72, "RW", 21],
    ["Alexis Claude-Maurice", 75, "LW/CAM", 27],
    ["Samuel Essende", 73, "ST", 27]
  ]},
  { name:"FC St. Pauli", short:"St. Pauli", tier:4, kit:{p:"#5A3E2B",s:"#FFFFFF",t:"#FFFFFF"}, players:[
    ["Nikola Vasilj", 76, "GK", 29],
    ["Ben Voll", 69, "GK", 24],
    ["Hauke Wahl", 73, "CB", 31],
    ["Eric Smith", 75, "CB/CDM", 28],
    ["Adam Dźwigała", 70, "CB", 29],
    ["Manolis Saliakas", 73, "RWB/RB", 29],
    ["Louis Oppie", 71, "LWB/LB", 23],
    ["Jackson Irvine", 74, "CM", 32],
    ["Joel Fujita", 72, "CDM/CM", 23],
    ["Connor Metcalfe", 72, "CM/LM", 26],
    ["Danel Sinani", 72, "RW/ST", 28],
    ["Oladapo Afolayan", 73, "LW", 28],
    ["Andréas Hountondji", 72, "ST", 23]
  ]},
  { name:"1. FC Heidenheim", short:"Heidenheim", tier:4, kit:{p:"#E30613",s:"#003E7E",t:"#FFFFFF"}, players:[
    ["Kevin Müller", 74, "GK", 34],
    ["Paul Tschernuth", 68, "GK", 23],
    ["Patrick Mainka", 74, "CB", 31],
    ["Tim Siersleben", 71, "CB", 25],
    ["Benedikt Gimber", 70, "CB/CDM", 28],
    ["Marnon Busch", 72, "RB", 30],
    ["Jonas Föhrenbach", 71, "LB", 29],
    ["Niklas Dorsch", 72, "CDM/CM", 27],
    ["Adrian Beck", 72, "CM/CAM", 28],
    ["Julian Niehues", 70, "CM", 24],
    ["Marvin Pieringer", 72, "RW/ST", 26],
    ["Mathias Honsak", 71, "LW", 28],
    ["Budu Zivzivadze", 73, "ST", 31]
  ]},
  { name:"1. FC Köln", short:"Köln", tier:4, kit:{p:"#FFFFFF",s:"#ED1C24",t:"#ED1C24"}, players:[
    ["Marvin Schwäbe", 74, "GK", 30],
    ["Ron-Robert Zieler", 69, "GK", 36],
    ["Timo Hübers", 73, "CB", 29],
    ["Joël Schmied", 72, "CB", 27],
    ["Rav van den Berg", 73, "CB", 21],
    ["Sebastian Sebulonsen", 71, "RB", 25],
    ["Leart Pacarada", 72, "LB", 31],
    ["Eric Martel", 73, "CDM/CM", 23],
    ["Denis Huseinbašić", 72, "CM", 24],
    ["Florian Kainz", 73, "CAM/LM", 33],
    ["Jakub Kamiński", 74, "RW/LW", 23],
    ["Saïd El Mala", 75, "LW/RW", 19],
    ["Ragnar Ache", 73, "ST", 27]
  ]},
  { name:"Hamburger SV", short:"HSV", tier:4, kit:{p:"#FFFFFF",s:"#0A3F86",t:"#0A3F86"}, players:[
    ["Daniel Heuer Fernandes", 74, "GK", 32],
    ["Daniel Peretz", 72, "GK", 25],
    ["Luka Vušković", 74, "CB", 18],
    ["Jordan Torunarigha", 72, "CB", 28],
    ["Daniel Elfadli", 72, "CB/CDM", 28],
    ["Giorgi Gocholeishvili", 70, "RB", 24],
    ["Miro Muheim", 73, "LB/LWB", 27],
    ["Jonas Meffert", 71, "CDM", 31],
    ["Albert Sambi Lokonga", 74, "CM/CDM", 26],
    ["Fábio Vieira", 76, "CAM", 25],
    ["Ransford Königsdörffer", 72, "RW/ST", 24],
    ["Jean-Luc Dompé", 72, "LW", 30],
    ["Yussuf Poulsen", 73, "ST", 31]
  ]}
];
