/* ELF '26 — Squad data. The REAL 48 official 2026 World Cup squads
   (Wikipedia: 2026 FIFA World Cup squads), 16 players each.
   [name, rating, positions("/"-sep, primary first), age]. Aggressive 2025/26 ratings. */
const ROSTERS = {
  ARG: { coach: "Lionel Scaloni", players: [
    ["Emiliano Martínez", 88, "GK", 33],
    ["Gerónimo Rulli", 80, "GK", 33],
    ["Cristian Romero", 88, "CB", 28],
    ["Lisandro Martínez", 85, "CB/LB", 28],
    ["Nicolás Otamendi", 82, "CB", 38],
    ["Nahuel Molina", 82, "RB/RWB", 28],
    ["Nicolás Tagliafico", 81, "LB/LWB", 33],
    ["Leandro Paredes", 82, "CDM/CM", 31],
    ["Rodrigo De Paul", 85, "CM", 31],
    ["Enzo Fernández", 87, "CM/CAM", 25],
    ["Alexis Mac Allister", 89, "CM/CAM", 27],
    ["Nico Paz", 84, "CAM/CM", 21],
    ["Lionel Messi", 90, "RW/CAM", 38],
    ["Nicolás González", 82, "LW/RW", 27],
    ["Lautaro Martínez", 90, "ST", 28],
    ["Julián Álvarez", 90, "ST/CAM", 26]
  ]},
  FRA: { coach: "Didier Deschamps", players: [
    ["Mike Maignan", 88, "GK", 30],
    ["Brice Samba", 80, "GK", 31],
    ["William Saliba", 90, "CB", 25],
    ["Dayot Upamecano", 86, "CB", 27],
    ["Ibrahima Konaté", 85, "CB", 26],
    ["Jules Koundé", 87, "RB/CB", 27],
    ["Théo Hernández", 85, "LB/LWB", 28],
    ["Aurélien Tchouaméni", 88, "CDM/CB", 26],
    ["Adrien Rabiot", 85, "CM", 31],
    ["Manu Koné", 84, "CM/CDM", 24],
    ["Warren Zaïre-Emery", 83, "CM/CDM", 20],
    ["Ousmane Dembélé", 93, "RW/ST", 28],
    ["Michael Olise", 89, "RW/CAM", 24],
    ["Désiré Doué", 87, "CAM/LW", 20],
    ["Kylian Mbappé", 95, "ST/LW", 27],
    ["Marcus Thuram", 85, "ST", 28]
  ]},
  ESP: { coach: "Luis de la Fuente", players: [
    ["Unai Simón", 85, "GK", 28],
    ["David Raya", 85, "GK", 30],
    ["Pau Cubarsí", 85, "CB", 19],
    ["Aymeric Laporte", 83, "CB", 31],
    ["Eric García", 82, "CB/RB", 25],
    ["Pedro Porro", 83, "RB/RWB", 26],
    ["Marc Cucurella", 85, "LB/LWB", 27],
    ["Rodri", 92, "CDM/CM", 29],
    ["Martín Zubimendi", 86, "CDM/CM", 26],
    ["Pedri", 91, "CM/CAM", 23],
    ["Mikel Merino", 84, "CM", 30],
    ["Dani Olmo", 87, "CAM", 27],
    ["Lamine Yamal", 94, "RW", 18],
    ["Nico Williams", 90, "LW/RW", 23],
    ["Ferran Torres", 84, "ST/LW", 26],
    ["Mikel Oyarzabal", 85, "ST", 29]
  ]},
  ENG: { coach: "Thomas Tuchel", players: [
    ["Jordan Pickford", 85, "GK", 32],
    ["Dean Henderson", 80, "GK", 29],
    ["John Stones", 84, "CB", 31],
    ["Marc Guéhi", 85, "CB", 25],
    ["Ezri Konsa", 81, "CB/RB", 28],
    ["Reece James", 84, "RB/RWB", 26],
    ["Tino Livramento", 80, "RB/LB", 23],
    ["Nico O'Reilly", 79, "LB/LWB", 20],
    ["Declan Rice", 90, "CDM/CM", 27],
    ["Kobbie Mainoo", 84, "CM/CDM", 20],
    ["Jude Bellingham", 92, "CAM/CM", 22],
    ["Eberechi Eze", 85, "CAM/LW", 27],
    ["Bukayo Saka", 91, "RW/RM", 24],
    ["Anthony Gordon", 83, "LW", 25],
    ["Harry Kane", 92, "ST", 32],
    ["Ollie Watkins", 84, "ST", 30]
  ]},
  BRA: { coach: "Carlo Ancelotti", players: [
    ["Alisson", 90, "GK", 33],
    ["Ederson", 84, "GK", 32],
    ["Marquinhos", 87, "CB", 31],
    ["Gabriel Magalhães", 88, "CB", 28],
    ["Bremer", 84, "CB", 28],
    ["Danilo", 80, "RB/CB", 34],
    ["Alex Sandro", 78, "LB", 35],
    ["Bruno Guimarães", 88, "CM/CDM", 28],
    ["Casemiro", 83, "CDM", 34],
    ["Lucas Paquetá", 84, "CAM/CM", 28],
    ["Neymar", 87, "CAM/LW", 34],
    ["Vinícius Júnior", 92, "LW", 25],
    ["Raphinha", 90, "RW/LW", 29],
    ["Gabriel Martinelli", 84, "LW", 24],
    ["Matheus Cunha", 84, "ST/LW", 26],
    ["Endrick", 82, "ST", 19]
  ]},
  POR: { coach: "Roberto Martínez", players: [
    ["Diogo Costa", 86, "GK", 26],
    ["José Sá", 80, "GK", 33],
    ["Rúben Dias", 90, "CB", 28],
    ["Gonçalo Inácio", 84, "CB/LB", 24],
    ["Tomás Araújo", 80, "CB", 23],
    ["Diogo Dalot", 84, "RB/LB", 26],
    ["Nuno Mendes", 89, "LB/LWB", 23],
    ["Vitinha", 91, "CM/CAM", 26],
    ["João Neves", 89, "CM/CDM", 21],
    ["Rúben Neves", 82, "CDM/CM", 29],
    ["Bruno Fernandes", 91, "CAM/CM", 31],
    ["Bernardo Silva", 88, "CAM/RW", 31],
    ["Rafael Leão", 89, "LW/ST", 26],
    ["Pedro Neto", 84, "RW/LW", 25],
    ["Cristiano Ronaldo", 86, "ST", 41],
    ["Gonçalo Ramos", 83, "ST", 24]
  ]},
  NED: { coach: "Ronald Koeman", players: [
    ["Bart Verbruggen", 84, "GK", 23],
    ["Mark Flekken", 79, "GK", 32],
    ["Virgil van Dijk", 90, "CB", 34],
    ["Micky van de Ven", 85, "CB/LB", 24],
    ["Jan Paul van Hecke", 80, "CB", 25],
    ["Denzel Dumfries", 85, "RWB/RB", 30],
    ["Jorrel Hato", 81, "LB/CB", 20],
    ["Nathan Aké", 83, "LB/CB", 31],
    ["Frenkie de Jong", 89, "CM/CDM", 28],
    ["Tijjani Reijnders", 87, "CM/CAM", 27],
    ["Ryan Gravenberch", 87, "CM/CDM", 23],
    ["Teun Koopmeiners", 83, "CAM/CM", 28],
    ["Cody Gakpo", 89, "LW/ST", 26],
    ["Justin Kluivert", 82, "RW/LW", 26],
    ["Memphis Depay", 84, "ST/CAM", 32],
    ["Wout Weghorst", 80, "ST", 33]
  ]},
  GER: { coach: "Julian Nagelsmann", players: [
    ["Manuel Neuer", 87, "GK", 40],
    ["Oliver Baumann", 79, "GK", 35],
    ["Antonio Rüdiger", 87, "CB", 33],
    ["Jonathan Tah", 84, "CB", 30],
    ["Nico Schlotterbeck", 85, "CB/LB", 26],
    ["Joshua Kimmich", 88, "RB/CDM", 31],
    ["David Raum", 81, "LB/LWB", 28],
    ["Aleksandar Pavlović", 84, "CDM/CM", 21],
    ["Leon Goretzka", 84, "CM", 31],
    ["Angelo Stiller", 83, "CDM/CM", 24],
    ["Florian Wirtz", 92, "CAM/LW", 23],
    ["Jamal Musiala", 92, "CAM/RW", 23],
    ["Leroy Sané", 84, "RW/LW", 30],
    ["Jamie Leweling", 80, "LW/RW", 24],
    ["Kai Havertz", 85, "ST/CAM", 27],
    ["Nick Woltemade", 83, "ST", 24]
  ]},
  BEL: { coach: "Rudi Garcia", players: [
    ["Thibaut Courtois", 90, "GK", 34],
    ["Senne Lammens", 79, "GK", 23],
    ["Zeno Debast", 81, "CB", 22],
    ["Arthur Theate", 81, "CB/LB", 25],
    ["Koni De Winter", 81, "CB", 24],
    ["Timothy Castagne", 80, "RB/RWB", 30],
    ["Maxim De Cuyper", 80, "LB/LWB", 25],
    ["Kevin De Bruyne", 91, "CAM/CM", 34],
    ["Youri Tielemans", 85, "CM/CDM", 28],
    ["Amadou Onana", 84, "CDM/CM", 24],
    ["Hans Vanaken", 80, "CM/CAM", 33],
    ["Jérémy Doku", 88, "LW/RW", 23],
    ["Alexis Saelemaekers", 83, "RW/RM", 26],
    ["Leandro Trossard", 84, "LW/ST", 31],
    ["Romelu Lukaku", 85, "ST", 32],
    ["Charles De Ketelaere", 83, "ST/CAM", 24]
  ]},
  CRO: { coach: "Zlatko Dalić", players: [
    ["Dominik Livaković", 82, "GK", 31],
    ["Ivor Pandur", 77, "GK", 26],
    ["Josip Šutalo", 81, "CB", 25],
    ["Marin Pongračić", 80, "CB", 28],
    ["Duje Ćaleta-Car", 79, "CB", 29],
    ["Josip Stanišić", 83, "RB/CB", 26],
    ["Joško Gvardiol", 88, "LB/CB", 24],
    ["Luka Modrić", 86, "CM/CAM", 40],
    ["Mateo Kovačić", 85, "CM/CDM", 31],
    ["Luka Sučić", 81, "CM/CAM", 23],
    ["Mario Pašalić", 82, "CAM/CM", 31],
    ["Nikola Vlašić", 81, "CAM/RW", 28],
    ["Ivan Perišić", 82, "LW/LWB", 37],
    ["Andrej Kramarić", 82, "ST/CAM", 34],
    ["Ante Budimir", 80, "ST", 34],
    ["Petar Musa", 80, "ST", 28]
  ]},
  URU: { coach: "Marcelo Bielsa", players: [
    ["Sergio Rochet", 80, "GK", 32],
    ["Santiago Mele", 76, "GK", 28],
    ["Ronald Araújo", 87, "CB/RB", 26],
    ["José María Giménez", 85, "CB", 31],
    ["Sebastián Cáceres", 80, "CB", 26],
    ["Guillermo Varela", 79, "RB/RWB", 32],
    ["Mathías Olivera", 81, "LB/LWB", 28],
    ["Rodrigo Aguirre", 80, "ST", 31],
    ["Manuel Ugarte", 83, "CDM/CM", 24],
    ["Federico Valverde", 90, "CM/RB", 27],
    ["Rodrigo Bentancur", 84, "CM/CDM", 28],
    ["Nicolás de la Cruz", 83, "CAM/CM", 28],
    ["Giorgian de Arrascaeta", 84, "CAM", 31],
    ["Facundo Pellistri", 79, "RW/RM", 24],
    ["Maximiliano Araújo", 79, "LW/LM", 25],
    ["Darwin Núñez", 85, "ST", 26]
  ]},
  MAR: { coach: "Mohamed Ouahbi", players: [
    ["Yassine Bounou", 85, "GK", 35],
    ["Munir Mohamedi", 76, "GK", 36],
    ["Nayef Aguerd", 83, "CB", 29],
    ["Chadi Riad", 80, "CB", 22],
    ["Issa Diop", 78, "CB", 29],
    ["Achraf Hakimi", 91, "RB/RWB", 27],
    ["Noussair Mazraoui", 83, "RB/LB", 28],
    ["Anass Salah-Eddine", 77, "LB/LWB", 23],
    ["Sofyan Amrabat", 82, "CDM/CM", 29],
    ["Azzedine Ounahi", 81, "CM/CAM", 25],
    ["Ismael Saibari", 82, "CM/CAM", 24],
    ["Bilal El Khannouss", 82, "CAM/CM", 21],
    ["Brahim Díaz", 85, "CAM/RW", 26],
    ["Abde Ezzalzouli", 81, "LW", 24],
    ["Soufiane Rahimi", 79, "ST", 29],
    ["Ayoub El Kaabi", 80, "ST", 32]
  ]},
  COL: { coach: "Néstor Lorenzo", players: [
    ["David Ospina", 79, "GK", 37],
    ["Camilo Vargas", 79, "GK", 36],
    ["Davinson Sánchez", 83, "CB", 29],
    ["Jhon Lucumí", 81, "CB", 27],
    ["Yerry Mina", 79, "CB", 31],
    ["Daniel Muñoz", 83, "RB/RWB", 29],
    ["Johan Mojica", 78, "LB/LWB", 33],
    ["Deiver Machado", 77, "LB", 32],
    ["Kevin Castaño", 81, "CDM/CM", 25],
    ["Jefferson Lerma", 81, "CDM/CM", 31],
    ["Richard Ríos", 83, "CM", 25],
    ["James Rodríguez", 84, "CAM", 34],
    ["Juan Fernando Quintero", 81, "CAM", 33],
    ["Jhon Arias", 82, "RW/CAM", 28],
    ["Luis Díaz", 90, "LW/ST", 29],
    ["Jhon Córdoba", 80, "ST", 32]
  ]},
  NOR: { coach: "Ståle Solbakken", players: [
    ["Ørjan Nyland", 79, "GK", 35],
    ["Egil Selvik", 74, "GK", 29],
    ["Kristoffer Ajer", 81, "CB/RB", 27],
    ["Leo Østigård", 79, "CB", 26],
    ["Torbjørn Heggem", 77, "CB", 26],
    ["Julian Ryerson", 81, "RB/LB", 28],
    ["David Møller Wolfe", 76, "LB/LWB", 23],
    ["Sander Berge", 81, "CM/CDM", 28],
    ["Patrick Berg", 78, "CDM/CM", 28],
    ["Fredrik Aursnes", 81, "CM/RM", 30],
    ["Martin Ødegaard", 89, "CAM/CM", 27],
    ["Antonio Nusa", 83, "LW/RW", 21],
    ["Oscar Bobb", 81, "RW/LW", 22],
    ["Erling Haaland", 94, "ST", 25],
    ["Alexander Sørloth", 84, "ST", 30],
    ["Jørgen Strand Larsen", 81, "ST", 26]
  ]},
  JPN: { coach: "Hajime Moriyasu", players: [
    ["Zion Suzuki", 81, "GK", 23],
    ["Keisuke Ōsako", 78, "GK", 26],
    ["Kō Itakura", 82, "CB", 29],
    ["Takehiro Tomiyasu", 81, "CB/RB", 27],
    ["Tsuyoshi Watanabe", 79, "CB", 29],
    ["Hiroki Itō", 81, "CB/LB", 27],
    ["Yukinari Sugawara", 79, "RB/RWB", 25],
    ["Wataru Endo", 82, "CDM/CM", 33],
    ["Ao Tanaka", 81, "CM/CDM", 27],
    ["Daichi Kamada", 83, "CAM/CM", 29],
    ["Kaishu Sano", 79, "CM/CDM", 24],
    ["Takefusa Kubo", 85, "RW/CAM", 24],
    ["Ritsu Dōan", 82, "RW/LW", 27],
    ["Daizen Maeda", 81, "LW/ST", 28],
    ["Ayase Ueda", 80, "ST", 27],
    ["Kōki Ogawa", 78, "ST", 28]
  ]},
  SEN: { coach: "Pape Thiaw", players: [
    ["Édouard Mendy", 83, "GK", 34],
    ["Yehvann Diouf", 77, "GK", 26],
    ["Kalidou Koulibaly", 83, "CB", 35],
    ["Abdoulaye Seck", 78, "CB", 33],
    ["Moussa Niakhaté", 80, "CB", 30],
    ["Krépin Diatta", 80, "RB/RM", 27],
    ["Antoine Mendy", 76, "RB/RWB", 22],
    ["Ismail Jakobs", 78, "LB/LWB", 26],
    ["Idrissa Gueye", 81, "CM/CDM", 36],
    ["Pape Matar Sarr", 83, "CM/CAM", 23],
    ["Lamine Camara", 81, "CM/CDM", 22],
    ["Habib Diarra", 80, "CM", 22],
    ["Ismaïla Sarr", 83, "RW/LW", 28],
    ["Sadio Mané", 84, "LW/ST", 34],
    ["Nicolas Jackson", 82, "ST", 24],
    ["Iliman Ndiaye", 81, "CAM/ST", 26]
  ]},
  MEX: { coach: "Javier Aguirre", players: [
    ["Guillermo Ochoa", 78, "GK", 40],
    ["Raúl Rangel", 80, "GK", 26],
    ["César Montes", 81, "CB", 28],
    ["Johan Vásquez", 81, "CB/LB", 27],
    ["Israel Reyes", 78, "CB/RB", 25],
    ["Jorge Sánchez", 77, "RB/RWB", 28],
    ["Jesús Gallardo", 78, "LB/LWB", 31],
    ["Mateo Chávez", 76, "LB", 21],
    ["Edson Álvarez", 84, "CDM/CM", 28],
    ["Luis Romo", 79, "CM/CB", 30],
    ["Luis Chávez", 80, "CM", 29],
    ["Orbelín Pineda", 81, "CAM/CM", 30],
    ["Gilberto Mora", 79, "CAM/CM", 17],
    ["Roberto Alvarado", 80, "RW/LW", 27],
    ["Santiago Giménez", 83, "ST", 25],
    ["Raúl Jiménez", 79, "ST", 35]
  ]},
  SWE: { coach: "Graham Potter", players: [
    ["Robin Olsen", 79, "GK", 36],
    ["Viktor Johansson", 77, "GK", 27],
    ["Victor Lindelöf", 81, "CB", 31],
    ["Isak Hien", 82, "CB", 26],
    ["Hjalmar Ekdal", 77, "CB", 27],
    ["Gabriel Gudmundsson", 80, "LB/LWB", 26],
    ["Daniel Svensson", 79, "RB/LB", 23],
    ["Lucas Bergvall", 82, "CM/CDM", 20],
    ["Yasin Ayari", 80, "CM", 22],
    ["Mattias Svanberg", 81, "CM/CDM", 27],
    ["Jesper Karlström", 78, "CDM/CM", 30],
    ["Benjamin Nygren", 80, "CAM/RW", 24],
    ["Anthony Elanga", 84, "RW/LW", 24],
    ["Ken Sema", 78, "LW/LM", 32],
    ["Alexander Isak", 91, "ST", 26],
    ["Viktor Gyökeres", 89, "ST", 28]
  ]},
  USA: { coach: "Mauricio Pochettino", players: [
    ["Matt Turner", 80, "GK", 32],
    ["Matt Freese", 77, "GK", 27],
    ["Chris Richards", 82, "CB", 26],
    ["Tim Ream", 77, "CB/LB", 38],
    ["Miles Robinson", 79, "CB", 29],
    ["Sergiño Dest", 81, "RB/RWB", 25],
    ["Antonee Robinson", 84, "LB/LWB", 28],
    ["Ricardo Pepi", 81, "ST", 23],
    ["Tyler Adams", 82, "CDM/CM", 27],
    ["Weston McKennie", 82, "CM/CAM", 28],
    ["Sebastian Berhalter", 78, "CM/CDM", 24],
    ["Malik Tillman", 82, "CAM", 23],
    ["Giovanni Reyna", 80, "CAM", 23],
    ["Christian Pulisic", 86, "LW/RW", 27],
    ["Timothy Weah", 80, "RW/RM", 26],
    ["Folarin Balogun", 81, "ST", 24]
  ]},
  SUI: { coach: "Murat Yakin", players: [
    ["Gregor Kobel", 85, "GK", 28],
    ["Yvon Mvogo", 78, "GK", 31],
    ["Manuel Akanji", 85, "CB/RB", 31],
    ["Nico Elvedi", 80, "CB", 29],
    ["Aurèle Amenda", 78, "CB", 22],
    ["Silvan Widmer", 78, "RB/RWB", 33],
    ["Ricardo Rodríguez", 79, "LB/CB", 33],
    ["Miro Muheim", 77, "LB/LWB", 28],
    ["Granit Xhaka", 85, "CDM/CM", 33],
    ["Remo Freuler", 81, "CM/CDM", 34],
    ["Denis Zakaria", 83, "CDM/CM", 29],
    ["Ardon Jashari", 81, "CM/CAM", 23],
    ["Rubén Vargas", 81, "LW/RW", 27],
    ["Dan Ndoye", 83, "RW/LW", 25],
    ["Breel Embolo", 81, "ST", 29],
    ["Noah Okafor", 80, "ST/LW", 26]
  ]},
  AUT: { coach: "Ralf Rangnick", players: [
    ["Alexander Schlager", 80, "GK", 30],
    ["Patrick Pentz", 78, "GK", 29],
    ["David Alaba", 84, "CB/LB", 34],
    ["Kevin Danso", 81, "CB", 27],
    ["Philipp Lienhart", 80, "CB", 29],
    ["Stefan Posch", 79, "RB/CB", 29],
    ["Phillipp Mwene", 77, "LB/RB", 32],
    ["Nicolas Seiwald", 81, "CDM/CM", 25],
    ["Xaver Schlager", 82, "CM/CDM", 28],
    ["Konrad Laimer", 84, "CM/RB", 28],
    ["Marcel Sabitzer", 83, "CM/CAM", 32],
    ["Romano Schmid", 80, "CAM/CM", 26],
    ["Patrick Wimmer", 80, "LW/RW", 25],
    ["Paul Wanner", 81, "CAM/LW", 20],
    ["Marko Arnautović", 80, "ST", 37],
    ["Michael Gregoritsch", 79, "ST", 32]
  ]},
  KOR: { coach: "Hong Myung-bo", players: [
    ["Kim Seung-gyu", 78, "GK", 35],
    ["Jo Hyeon-woo", 79, "GK", 34],
    ["Kim Min-jae", 85, "CB", 30],
    ["Cho Yu-min", 78, "CB", 29],
    ["Lee Tae-seok", 76, "CB", 23],
    ["Kim Tae-hyeon", 76, "RB/CB", 25],
    ["Kim Moon-hwan", 77, "RB/RWB", 30],
    ["Lee Han-beom", 76, "LB/LWB", 26],
    ["Hwang In-beom", 82, "CM/CDM", 29],
    ["Paik Seung-ho", 79, "CDM/CM", 28],
    ["Lee Jae-sung", 81, "CAM/CM", 33],
    ["Bae Jun-ho", 80, "CAM", 22],
    ["Lee Kang-in", 84, "CAM/RW", 24],
    ["Son Heung-min", 87, "LW/ST", 33],
    ["Hwang Hee-chan", 81, "RW/ST", 29],
    ["Oh Hyeon-gyu", 78, "ST", 24]
  ]},
  TUR: { coach: "Vincenzo Montella", players: [
    ["Uğurcan Çakır", 82, "GK", 29],
    ["Mert Günok", 79, "GK", 36],
    ["Merih Demiral", 82, "CB", 27],
    ["Çağlar Söyüncü", 80, "CB", 29],
    ["Abdülkerim Bardakçı", 79, "CB", 31],
    ["Zeki Çelik", 79, "RB/RWB", 28],
    ["Mert Müldür", 78, "RB", 26],
    ["Ferdi Kadıoğlu", 81, "LB/RB", 26],
    ["Hakan Çalhanoğlu", 86, "CDM/CM", 31],
    ["Orkun Kökçü", 81, "CM/CDM", 25],
    ["İsmail Yüksek", 78, "CDM/CM", 26],
    ["Arda Güler", 85, "CAM/RW", 21],
    ["Kenan Yıldız", 85, "LW/CAM", 20],
    ["Kerem Aktürkoğlu", 82, "LW/RW", 27],
    ["Barış Alper Yılmaz", 80, "RW/ST", 25],
    ["Can Uzun", 80, "CAM/ST", 20]
  ]},
  ECU: { coach: "Sebastián Beccacece", players: [
    ["Hernán Galíndez", 78, "GK", 39],
    ["Moisés Ramírez", 77, "GK", 25],
    ["Willian Pacho", 86, "CB", 24],
    ["Piero Hincapié", 85, "CB/LB", 24],
    ["Félix Torres", 79, "CB", 29],
    ["Joel Ordóñez", 80, "CB", 21],
    ["Ángelo Preciado", 78, "RB/RWB", 28],
    ["Pervis Estupiñán", 82, "LB/LWB", 28],
    ["Moisés Caicedo", 88, "CDM/CM", 24],
    ["Alan Franco", 78, "CM/CB", 29],
    ["Jordy Alcívar", 77, "CM/CDM", 25],
    ["Kendry Páez", 80, "CAM/CM", 18],
    ["Gonzalo Plata", 81, "RW/LW", 25],
    ["Nilson Angulo", 78, "LW", 22],
    ["Enner Valencia", 80, "ST", 36],
    ["Kevin Rodríguez", 78, "ST", 25]
  ]},
  CAN: { coach: "Jesse Marsch", players: [
    ["Dayne St. Clair", 79, "GK", 28],
    ["Maxime Crépeau", 77, "GK", 31],
    ["Alistair Johnston", 80, "RB/CB", 27],
    ["Moïse Bombito", 80, "CB", 25],
    ["Derek Cornelius", 78, "CB", 28],
    ["Joel Waterman", 75, "CB", 29],
    ["Richie Laryea", 76, "RB/RWB", 31],
    ["Alphonso Davies", 85, "LB/LW", 25],
    ["Stephen Eustáquio", 81, "CM/CDM", 29],
    ["Ismaël Koné", 79, "CM/CDM", 23],
    ["Mathieu Choinière", 77, "CM", 26],
    ["Jonathan Osorio", 77, "CAM/CM", 33],
    ["Tajon Buchanan", 80, "RW/RWB", 26],
    ["Jacob Shaffelburg", 78, "LW/LM", 26],
    ["Jonathan David", 85, "ST", 26],
    ["Cyle Larin", 79, "ST", 30]
  ]},
  CIV: { coach: "Emerse Faé", players: [
    ["Yahia Fofana", 79, "GK", 25],
    ["Alban Lafont", 79, "GK", 27],
    ["Ousmane Diomande", 82, "CB", 22],
    ["Evan Ndicka", 82, "CB", 26],
    ["Odilon Kossounou", 81, "CB", 25],
    ["Wilfried Singo", 83, "RB/RWB", 25],
    ["Ghislain Konan", 77, "LB/LWB", 30],
    ["Franck Kessié", 84, "CM/CDM", 29],
    ["Ibrahim Sangaré", 82, "CDM/CM", 28],
    ["Seko Fofana", 82, "CM/CAM", 30],
    ["Jean Michaël Seri", 79, "CM/CDM", 34],
    ["Amad Diallo", 85, "RW/RM", 23],
    ["Simon Adingra", 82, "LW/RW", 24],
    ["Nicolas Pépé", 81, "RW", 30],
    ["Evann Guessand", 81, "ST/LW", 24],
    ["Sébastien Haller", 80, "ST", 31]
  ]},
  CZE: { coach: "Ivan Hašek", players: [
    ["Jindřich Staněk", 81, "GK", 29],
    ["Matěj Kovář", 79, "GK", 25],
    ["Ladislav Krejčí", 83, "CB", 26],
    ["Robin Hranáč", 79, "CB", 25],
    ["David Zima", 78, "CB", 25],
    ["Tomáš Holeš", 79, "CB/CDM", 32],
    ["Vladimír Coufal", 80, "RB/RWB", 33],
    ["David Jurásek", 78, "LB/LWB", 25],
    ["Tomáš Souček", 84, "CM/CDM", 31],
    ["Lukáš Červ", 78, "CM", 24],
    ["Michal Sadílek", 78, "CDM/CM", 26],
    ["Lukáš Provod", 81, "CM/LW", 29],
    ["Pavel Šulc", 82, "CAM/RW", 25],
    ["Adam Hložek", 82, "ST/LW", 23],
    ["Patrik Schick", 85, "ST", 30],
    ["Tomáš Chorý", 79, "ST", 30]
  ]},
  EGY: { coach: "Hossam Hassan", players: [
    ["Mohamed El Shenawy", 80, "GK", 37],
    ["Mostafa Shobeir", 76, "GK", 28],
    ["Mohamed Abdelmonem", 79, "CB", 27],
    ["Ramy Rabia", 77, "CB", 31],
    ["Yasser Ibrahim", 77, "CB", 30],
    ["Mohamed Hany", 76, "RB/RWB", 30],
    ["Ahmed Fatouh", 76, "LB/LWB", 28],
    ["Karim Hafez", 75, "LB", 30],
    ["Hamdy Fathy", 78, "CDM/CM", 31],
    ["Emam Ashour", 81, "CM/CAM", 27],
    ["Marwan Attia", 76, "CDM/CM", 24],
    ["Nabil Emad", 76, "CM", 22],
    ["Zizo", 80, "RW/CAM", 30],
    ["Trézéguet", 80, "LW/RW", 31],
    ["Mohamed Salah", 92, "RW/ST", 33],
    ["Omar Marmoush", 85, "ST/CAM", 27]
  ]},
  ALG: { coach: "Vladimir Petković", players: [
    ["Luca Zidane", 78, "GK", 27],
    ["Oussama Benbot", 75, "GK", 27],
    ["Aïssa Mandi", 80, "CB", 34],
    ["Mohamed Amine Tougai", 78, "CB", 24],
    ["Zineddine Belaïd", 76, "CB", 25],
    ["Rafik Belghali", 77, "RB/RWB", 23],
    ["Rayan Aït-Nouri", 85, "LB/LWB", 24],
    ["Ramy Bensebaini", 82, "LB/CB", 30],
    ["Ramiz Zerrouki", 79, "CDM/CM", 27],
    ["Nabil Bentaleb", 80, "CM/CDM", 31],
    ["Houssem Aouar", 82, "CAM/CM", 27],
    ["Farès Chaïbi", 81, "CM/CAM", 23],
    ["Ibrahim Maza", 80, "CAM", 20],
    ["Riyad Mahrez", 84, "RW", 35],
    ["Amine Gouiri", 83, "ST", 26],
    ["Mohamed Amoura", 84, "ST/LW", 25]
  ]},
  SCO: { coach: "Steve Clarke", players: [
    ["Angus Gunn", 79, "GK", 30],
    ["Craig Gordon", 77, "GK", 43],
    ["Jack Hendry", 79, "CB", 31],
    ["Grant Hanley", 78, "CB", 34],
    ["John Souttar", 79, "CB", 29],
    ["Scott McKenna", 78, "CB", 29],
    ["Aaron Hickey", 79, "RB/RWB", 24],
    ["Andy Robertson", 84, "LB/LWB", 32],
    ["Kieran Tierney", 81, "LB/CB", 28],
    ["Scott McTominay", 86, "CM/CAM", 29],
    ["John McGinn", 83, "CM/CAM", 31],
    ["Lewis Ferguson", 81, "CM/CDM", 26],
    ["Ryan Christie", 80, "CAM/RW", 31],
    ["Ben Doak", 80, "RW/LW", 20],
    ["Ché Adams", 80, "ST", 29],
    ["Lawrence Shankland", 79, "ST", 30]
  ]},
  GHA: { coach: "Otto Addo", players: [
    ["Lawrence Ati-Zigi", 78, "GK", 29],
    ["Benjamin Asare", 74, "GK", 29],
    ["Alidu Seidu", 78, "RB/CB", 25],
    ["Abdul Mumin", 78, "CB", 27],
    ["Jonas Adjetey", 76, "CB", 22],
    ["Jerome Opoku", 76, "CB", 27],
    ["Gideon Mensah", 76, "LB/LWB", 27],
    ["Thomas Partey", 84, "CDM/CM", 32],
    ["Elisha Owusu", 78, "CDM/CM", 28],
    ["Kwasi Sibo", 76, "CM/CDM", 27],
    ["Mohammed Kudus", 86, "CAM/RW", 25],
    ["Abdul Fatawu Issahaku", 81, "RW/LW", 21],
    ["Antoine Semenyo", 84, "RW/ST", 26],
    ["Kamaldeen Sulemana", 81, "LW", 24],
    ["Iñaki Williams", 81, "ST/RW", 31],
    ["Jordan Ayew", 80, "ST/CAM", 34]
  ]},
  IRN: { coach: "Amir Ghalenoei", players: [
    ["Alireza Beiranvand", 78, "GK", 33],
    ["Payam Niazmand", 76, "GK", 30],
    ["Hossein Kanaanizadegan", 77, "CB", 31],
    ["Shojae Khalilzadeh", 75, "CB", 36],
    ["Aria Yousefi", 74, "CB", 22],
    ["Ramin Rezaeian", 77, "RB/RWB", 35],
    ["Saleh Hardani", 75, "RB", 27],
    ["Ehsan Hajsafi", 77, "LB/LWB", 35],
    ["Saeid Ezatolahi", 78, "CDM/CM", 29],
    ["Rouzbeh Cheshmi", 77, "CM/CB", 32],
    ["Saman Ghoddos", 79, "CAM/CM", 32],
    ["Mehdi Torabi", 77, "CM/RW", 31],
    ["Alireza Jahanbakhsh", 78, "RW/RM", 32],
    ["Mohammad Mohebi", 76, "LW/RW", 27],
    ["Mehdi Taremi", 83, "ST", 33],
    ["Ali Alipour", 77, "ST", 29]
  ]},
  COD: { coach: "Sébastien Desabre", players: [
    ["Lionel Mpasi", 77, "GK", 31],
    ["Timothy Fayulu", 75, "GK", 30],
    ["Chancel Mbemba", 82, "CB", 31],
    ["Axel Tuanzebe", 78, "CB", 28],
    ["Dylan Batubinsika", 78, "CB", 29],
    ["Aaron Wan-Bissaka", 82, "RB/RWB", 28],
    ["Gédéon Kalulu", 77, "RB", 28],
    ["Arthur Masuaku", 79, "LB/LWB", 32],
    ["Noah Sadiki", 80, "CDM/CM", 21],
    ["Edo Kayembe", 79, "CM/CDM", 27],
    ["Charles Pickel", 78, "CM/CDM", 28],
    ["Gaël Kakuta", 79, "CAM/LW", 34],
    ["Théo Bongonda", 80, "LW/RW", 30],
    ["Yoane Wissa", 84, "ST/LW", 29],
    ["Cédric Bakambu", 80, "ST", 30],
    ["Fiston Mayele", 80, "ST", 31]
  ]},
  BIH: { coach: "Sergej Barbarez", players: [
    ["Nikola Vasilj", 78, "GK", 30],
    ["Mladen Jurkas", 73, "GK", 30],
    ["Nikola Katić", 78, "CB", 29],
    ["Dennis Hadžikadunić", 77, "CB", 27],
    ["Tarik Muharemović", 77, "CB", 22],
    ["Amar Dedić", 80, "RB/RWB", 23],
    ["Sead Kolašinac", 79, "LB/CB", 32],
    ["Benjamin Tahirović", 78, "CM/CDM", 22],
    ["Amir Hadžiahmetović", 77, "CDM/CM", 28],
    ["Ivan Šunjić", 76, "CDM/CM", 29],
    ["Armin Gigović", 76, "CM", 23],
    ["Esmir Bajraktarević", 79, "RW/LW", 20],
    ["Kerim Alajbegović", 77, "LW/CAM", 19],
    ["Ermedin Demirović", 81, "ST", 27],
    ["Edin Džeko", 81, "ST", 39],
    ["Haris Tabaković", 78, "ST", 31]
  ]},
  RSA: { coach: "Hugo Broos", players: [
    ["Ronwen Williams", 80, "GK", 33],
    ["Sipho Chaine", 75, "GK", 27],
    ["Nkosinathi Sibisi", 76, "CB", 28],
    ["Khulumani Ndamane", 75, "CB", 25],
    ["Mbekezeli Mbokazi", 75, "CB", 20],
    ["Khuliso Mudau", 77, "RB/RWB", 30],
    ["Aubrey Modiba", 77, "LB/LWB", 30],
    ["Iqraam Rayners", 78, "ST", 29],
    ["Teboho Mokoena", 80, "CM/CDM", 28],
    ["Thalente Mbatha", 76, "CM", 28],
    ["Sphephelo Sithole", 76, "CDM/CM", 26],
    ["Jayden Adams", 75, "CM", 24],
    ["Themba Zwane", 79, "CAM", 36],
    ["Oswin Appollis", 78, "RW/LW", 24],
    ["Relebohile Mofokeng", 78, "LW/RW", 21],
    ["Lyle Foster", 80, "ST", 25]
  ]},
  PAR: { coach: "Gustavo Alfaro", players: [
    ["Gatito Fernández", 78, "GK", 38],
    ["Orlando Gill", 75, "GK", 27],
    ["Gustavo Gómez", 81, "CB", 32],
    ["Omar Alderete", 80, "CB", 29],
    ["Fabián Balbuena", 78, "CB", 34],
    ["Júnior Alonso", 78, "CB/LB", 32],
    ["Juan Cáceres", 75, "RB/CB", 26],
    ["Andrés Cubas", 79, "CDM/CM", 30],
    ["Damián Bobadilla", 78, "CM", 22],
    ["Diego Gómez", 80, "CM/CAM", 22],
    ["Matías Galarza", 77, "CM", 23],
    ["Miguel Almirón", 81, "RW/CAM", 31],
    ["Ramón Sosa", 79, "LW/RW", 25],
    ["Julio Enciso", 81, "CAM/RW", 21],
    ["Antonio Sanabria", 79, "ST", 29],
    ["Álex Arce", 77, "ST", 29]
  ]},
  AUS: { coach: "Tony Popovic", players: [
    ["Mathew Ryan", 79, "GK", 34],
    ["Paul Izzo", 74, "GK", 31],
    ["Harry Souttar", 78, "CB", 27],
    ["Cameron Burgess", 75, "CB", 30],
    ["Alessandro Circati", 78, "CB", 22],
    ["Kai Trewin", 74, "CB", 25],
    ["Jason Geria", 74, "RB/RWB", 32],
    ["Aziz Behich", 76, "LB/LWB", 35],
    ["Jordan Bos", 78, "LB/LWB", 23],
    ["Aiden O'Neill", 77, "CDM/CM", 27],
    ["Connor Metcalfe", 76, "CM", 26],
    ["Cammy Devlin", 75, "CM/CDM", 27],
    ["Jackson Irvine", 78, "CM/CAM", 33],
    ["Mathew Leckie", 77, "RW/ST", 35],
    ["Nestory Irankunda", 77, "RW/LW", 20],
    ["Mohamed Touré", 75, "ST", 22]
  ]},
  TUN: { coach: "Sami Trabelsi", players: [
    ["Aymen Dahmen", 78, "GK", 28],
    ["Mouhib Chamakh", 74, "GK", 25],
    ["Montassar Talbi", 79, "CB", 27],
    ["Dylan Bronn", 77, "CB", 30],
    ["Omar Rekik", 76, "CB", 24],
    ["Yan Valery", 76, "RB/CB", 27],
    ["Hazem Mastouri", 76, "ST", 24],
    ["Ali Abdi", 76, "LB/LWB", 31],
    ["Ellyes Skhiri", 81, "CDM/CM", 31],
    ["Rani Khedira", 78, "CDM/CM", 32],
    ["Anis Ben Slimane", 77, "CM", 25],
    ["Hannibal Mejbri", 80, "CAM/CM", 23],
    ["Ismaël Gharbi", 77, "CAM/LW", 22],
    ["Elias Achouri", 79, "RW/LW", 27],
    ["Sebastian Tounekti", 78, "LW/RW", 24],
    ["Firas Chaouat", 76, "ST", 28]
  ]},
  KSA: { coach: "Hervé Renard", players: [
    ["Mohammed Al-Owais", 76, "GK", 34],
    ["Nawaf Al-Aqidi", 73, "GK", 25],
    ["Hassan Al-Tambakti", 76, "CB", 26],
    ["Abdulelah Al-Amri", 75, "CB", 28],
    ["Ali Lajami", 74, "CB", 28],
    ["Ali Majrashi", 73, "CB", 31],
    ["Saud Abdulhamid", 76, "RB/RWB", 26],
    ["Nawaf Boushal", 73, "LB/LWB", 25],
    ["Mohamed Kanno", 76, "CDM/CM", 31],
    ["Abdullah Al-Khaibari", 74, "CM/CDM", 29],
    ["Nasser Al-Dawsari", 75, "CM/LM", 27],
    ["Musab Al-Juwayr", 76, "CM/CAM", 21],
    ["Salem Al-Dawsari", 80, "LW", 34],
    ["Khalid Al-Ghannam", 76, "RW", 25],
    ["Firas Al-Buraikan", 78, "ST", 25],
    ["Saleh Al-Shehri", 75, "ST", 32]
  ]},
  PAN: { coach: "Thomas Christiansen", players: [
    ["Orlando Mosquera", 77, "GK", 31],
    ["Luis Mejía", 75, "GK", 34],
    ["José Córdoba", 79, "CB", 24],
    ["Fidel Escobar", 76, "CB", 30],
    ["Roderick Miller", 74, "CB", 32],
    ["Andrés Andrade", 76, "CB/CDM", 33],
    ["Michael Amir Murillo", 80, "RB/RWB", 30],
    ["Eric Davis", 74, "LB/LWB", 34],
    ["César Blackman", 74, "RB", 27],
    ["Adalberto Carrasquilla", 80, "CM/CDM", 27],
    ["Aníbal Godoy", 76, "CDM/CM", 36],
    ["Cristian Martínez", 76, "CM/CAM", 28],
    ["Ismael Díaz", 79, "CAM/RW", 28],
    ["José Luis Rodríguez", 77, "RW/LW", 27],
    ["José Fajardo", 77, "ST", 30],
    ["Cecilio Waterman", 77, "ST", 34]
  ]},
  UZB: { coach: "Fabio Cannavaro", players: [
    ["Utkir Yusupov", 77, "GK", 27],
    ["Abduvohid Nematov", 74, "GK", 26],
    ["Abdukodir Khusanov", 82, "CB/RB", 22],
    ["Rustam Ashurmatov", 77, "CB", 29],
    ["Farrukh Sayfiev", 75, "CB/RB", 27],
    ["Khojiakbar Alijonov", 75, "CB", 26],
    ["Umar Eshmurodov", 74, "LB/LWB", 25],
    ["Sherzod Nasrullaev", 74, "RB/RWB", 28],
    ["Otabek Shukurov", 78, "CDM/CM", 29],
    ["Odiljon Hamrobekov", 76, "CM/CDM", 29],
    ["Jamshid Iskanderov", 77, "CM/CAM", 31],
    ["Abbosbek Fayzullaev", 80, "CAM/RW", 22],
    ["Jaloliddin Masharipov", 78, "CAM/LW", 32],
    ["Oston Urunov", 76, "LW/RW", 25],
    ["Eldor Shomurodov", 81, "ST", 31],
    ["Igor Sergeev", 76, "ST", 32]
  ]},
  QAT: { coach: "Julen Lopetegui", players: [
    ["Meshaal Barsham", 76, "GK", 28],
    ["Salah Zakaria", 73, "GK", 26],
    ["Boualem Khoukhi", 76, "CB", 35],
    ["Pedro Miguel", 75, "CB/RB", 35],
    ["Lucas Mendes", 75, "CB/LB", 30],
    ["Tarek Salman", 74, "CB", 28],
    ["Homam Ahmed", 74, "LB/LWB", 28],
    ["Jassem Gaber", 74, "RB/RWB", 28],
    ["Karim Boudiaf", 76, "CDM/CM", 35],
    ["Assim Madibo", 76, "CDM/CM", 29],
    ["Abdulaziz Hatem", 75, "CM/CAM", 35],
    ["Ahmed Fathy", 74, "CM", 26],
    ["Akram Afif", 81, "LW/CAM", 29],
    ["Hassan Al-Haydos", 77, "CAM/RW", 35],
    ["Almoez Ali", 78, "ST", 29],
    ["Edmilson Junior", 77, "ST/RW", 31]
  ]},
  CPV: { coach: "Bubista", players: [
    ["Vozinha", 76, "GK", 39],
    ["Márcio Rosa", 72, "GK", 30],
    ["Roberto Lopes", 77, "CB", 33],
    ["Logan Costa", 79, "CB", 24],
    ["Diney", 75, "CB", 32],
    ["Stopira", 74, "LB/CB", 37],
    ["Steven Moreira", 77, "RB/RWB", 31],
    ["Sidny Lopes Cabral", 73, "LB", 25],
    ["Kevin Pina", 76, "CM/CDM", 27],
    ["Jamiro Monteiro", 79, "CM/CAM", 32],
    ["Deroy Duarte", 77, "CM/CDM", 26],
    ["Laros Duarte", 76, "CDM/CM", 28],
    ["Garry Rodrigues", 78, "RW/LW", 35],
    ["Jovane Cabral", 78, "LW/ST", 27],
    ["Dailon Livramento", 76, "ST", 24],
    ["Gilson Benchimol", 75, "ST", 23]
  ]},
  JOR: { coach: "Jamal Sellami", players: [
    ["Yazeed Abulaila", 75, "GK", 31],
    ["Abdallah Al-Fakhouri", 72, "GK", 27],
    ["Abdallah Nasib", 74, "CB", 29],
    ["Yazan Al-Arab", 74, "CB", 28],
    ["Ihsan Haddad", 73, "CB", 27],
    ["Mohammad Abu Hashish", 72, "CB", 28],
    ["Salim Obaid", 73, "RB/RWB", 26],
    ["Mohammad Taha", 72, "LB/LWB", 27],
    ["Amer Jamous", 74, "CDM/CM", 26],
    ["Noor Al-Rawabdeh", 75, "CM/CAM", 23],
    ["Nizar Al-Rashdan", 74, "CM", 27],
    ["Rajaei Ayed", 73, "CM/CDM", 26],
    ["Musa Al-Taamari", 81, "RW/LW", 28],
    ["Mahmoud Al-Mardi", 73, "LW/RM", 26],
    ["Yazan Al-Naimat", 77, "ST", 26],
    ["Ali Olwan", 76, "ST", 27]
  ]},
  IRQ: { coach: "Graham Arnold", players: [
    ["Jalal Hassan", 75, "GK", 31],
    ["Fahad Talib", 73, "GK", 30],
    ["Rebin Sulaka", 75, "CB", 28],
    ["Merchas Doski", 74, "CB", 25],
    ["Akam Hashim", 73, "CB", 26],
    ["Frans Putros", 74, "CB", 32],
    ["Hussein Ali", 74, "RB/RWB", 25],
    ["Manaf Younis", 73, "LB/LWB", 26],
    ["Amir Al-Ammari", 76, "CM/CDM", 28],
    ["Aimar Sher", 75, "CM", 24],
    ["Kevin Yakob", 75, "CM/RW", 25],
    ["Zidane Iqbal", 77, "CM/CAM", 22],
    ["Ibrahim Bayesh", 76, "CAM", 28],
    ["Ali Jasim", 77, "LW/CAM", 22],
    ["Aymen Hussein", 76, "ST", 29],
    ["Mohanad Ali", 77, "ST", 25]
  ]},
  NZL: { coach: "Darren Bazeley", players: [
    ["Max Crocombe", 75, "GK", 32],
    ["Alex Paulsen", 75, "GK", 23],
    ["Michael Boxall", 76, "CB", 37],
    ["Tyler Bindon", 77, "CB", 20],
    ["Finn Surman", 74, "CB", 22],
    ["Nando Pijnaker", 75, "CB", 27],
    ["Tim Payne", 74, "RB/RWB", 31],
    ["Liberato Cacace", 78, "LB/LWB", 25],
    ["Joe Bell", 76, "CM/CDM", 26],
    ["Marko Stamenić", 77, "CM", 23],
    ["Matthew Garbett", 75, "CM/CAM", 23],
    ["Alex Rufer", 74, "CDM/CM", 29],
    ["Ryan Thomas", 76, "CAM/RW", 31],
    ["Ben Old", 76, "RW/LW", 23],
    ["Chris Wood", 82, "ST", 34],
    ["Ben Waine", 74, "ST", 24]
  ]},
  HAI: { coach: "Sébastien Migné", players: [
    ["Johny Placide", 74, "GK", 38],
    ["Josué Duverger", 71, "GK", 28],
    ["Ricardo Adé", 74, "CB", 30],
    ["Hannes Delcroix", 76, "CB/LB", 26],
    ["Jean-Kévin Duverne", 75, "CB", 28],
    ["Carlens Arcus", 74, "RB/CB", 29],
    ["Wilguens Paugain", 72, "LB/LWB", 25],
    ["Duke Lacroix", 72, "RB/RWB", 29],
    ["Danley Jean Jacques", 76, "CDM/CM", 25],
    ["Carl Sainté", 75, "CM/CDM", 27],
    ["Leverton Pierre", 73, "CM", 23],
    ["Jean-Ricner Bellegarde", 79, "CAM/CM", 27],
    ["Derrick Etienne Jr.", 77, "RW/LW", 29],
    ["Ruben Providence", 75, "RW/LW", 24],
    ["Wilson Isidor", 78, "ST", 25],
    ["Frantzdy Pierrot", 76, "ST", 30]
  ]},
  CUW: { coach: "Dick Advocaat", players: [
    ["Eloy Room", 75, "GK", 37],
    ["Tyrick Bodak", 71, "GK", 24],
    ["Armando Obispo", 76, "CB", 27],
    ["Roshon van Eijma", 74, "CB", 27],
    ["Jurién Gaari", 74, "CB", 29],
    ["Sherel Floranus", 75, "RB/CB", 27],
    ["Gervane Kastaneer", 76, "ST", 29],
    ["Joshua Brenet", 76, "RB/LB", 31],
    ["Riechedly Bazoer", 78, "CDM/CB", 29],
    ["Leandro Bacuna", 77, "CM/RB", 34],
    ["Juninho Bacuna", 77, "CM/CAM", 28],
    ["Livano Comenencia", 75, "CM/RB", 22],
    ["Tahith Chong", 78, "RW/CAM", 26],
    ["Brandley Kuwas", 76, "RW/LW", 33],
    ["Kenji Gorré", 75, "LW/CAM", 31],
    ["Jürgen Locadia", 77, "ST", 32]
  ]}
};
if (typeof window !== 'undefined') { window.ROSTERS = ROSTERS; }
